<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
?>

    <span>(<?php echo $_productCollection->getSize(); ?>)</span>
</div>



<div class="product_sort">
    <?php
        $sortType = $this->getRequest()->getParam('order');
        $dir = $this->getRequest()->getParam('dir');
    ?>
    <script>
        jQuery(document).ready(function(){
            function updateQueryStringParameter(uri, key, value) {
                var re = new RegExp("([?&])" + key + "=.*?(&|$)", "i");
                var separator = uri.indexOf('?') !== -1 ? "&" : "?";
                if (uri.match(re)) {
                    return uri.replace(re, '$1' + key + "=" + value + '$2');
                }
                else {
                    return uri + separator + key + "=" + value;
                }
            }

            jQuery('#HOTSALE').on('click',function(){
                var url = updateQueryStringParameter(window.location.toString(), 'order', 'hot_sale');
                url = updateQueryStringParameter(url, 'dir', 'desc');
                window.location.href = url;
                return false;
            });

            jQuery('#NEW').on('click',function(){
                var url = updateQueryStringParameter(window.location.toString(), 'order', 'news_from_date');
                url = updateQueryStringParameter(url, 'dir', 'desc');
                window.location.href = url;
            });

            jQuery("#PRICE").on('click',function(){
                var price_id = jQuery(this).find('.price_on').prop('id');
                if(price_id){
                    if( price_id == 'LOW_PRICE'){
                        var url = updateQueryStringParameter(window.location.toString(), 'order', 'price');
                        url = updateQueryStringParameter(url, 'dir', 'desc');
                        window.location.href = url;
                    }
                    else if( price_id == 'HIGH_PRICE'){
                        var url = updateQueryStringParameter(window.location.toString(), 'order', 'price');
                        url = updateQueryStringParameter(url, 'dir', 'asc');
                        window.location.href = url;
                    }
                }else{
                    var url = updateQueryStringParameter(window.location.toString(), 'order', 'price');
                    url = updateQueryStringParameter(url, 'dir', 'asc');
                    window.location.href = url;
                }

            });

        });
    </script>


    <span id="HOTSALE" class="<?php if(empty($sortType) || $sortType == 'hot_sale') {echo 'on';}?>">
        <em></em>
        <span>Sales</span>
    </span>



    <span id="NEW" class="<?php if($sortType == 'news_from_date') {echo 'on';}?>">
        <em></em>
        <span>New</span>
    </span>



    <span id="PRICE" class="<?php if($sortType == 'price') {echo 'on';}?>">
        <em>
            <i id="LOW_PRICE" class="up<?php if ($sortType == 'price' && $dir == 'asc') {echo '-on price_on';}?>"></i>
            <i id="HIGH_PRICE" class="down<?php if ($sortType == 'price' && $dir == 'desc') {echo '-on price_on';}?>"></i>
        </em>
        <span>Price</span>
    </span>


</div>






<?php if(!$_productCollection->count()): ?>

    <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>

<?php else: ?>


    <div class="category-products">

    

        <?php $_collectionSize = $_productCollection->count() ?>
        <?php $_columnCount = $this->getColumnCount(); ?>

        <?php $i=0; foreach ($_productCollection as $_product): ?>
            <?php if ($i++%$_columnCount==0): ?>
            <ul class="products-grid">
            <?php endif ?>
                <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135); ?>" width="135" height="135" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
                    <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
                    <?php if($_product->getRatingSummary()): ?>
                    <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                    <?php endif; ?>
                    <?php echo $this->getPriceHtml($_product, true) ?>
                    <div class="actions">
                        <?php if($_product->isSaleable()): ?>
                            <button type="button" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Add to Cart')) ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                        <?php else: ?>
                            <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                        <?php endif; ?>
                        <ul class="add-to-links">
                            <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                            <?php endif; ?>
                            <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                                <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
                            <?php endif; ?>
                        </ul>
                    </div>
                </li>
            <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
            </ul>
            <?php endif ?>
        <?php endforeach ?>

        <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
        

        <div class="toolbar-bottom">
            <?php echo $this->getToolbarHtml() ?>
        </div>
    </div>


<?php endif; ?>
