<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
?>

<!-- Structured Data-->
<?php
$currCat = Mage::registry('current_category');
if($currCat):
    $prodCollection = Mage::getResourceModel('catalog/product_collection')->addCategoryFilter($currCat);
    $proids = array();
    foreach ($prodCollection as $pro) {
        $proids[] = $pro->getId();
    }
    $review1 = Mage::getModel('review/review')->getResourceCollection()
        ->addFieldToFilter('entity_pk_value', array('in' => $proids))
        ->addStoreFilter(Mage::app()->getStore()->getId())
        ->addStatusFilter(Mage_Review_Model_Review::STATUS_APPROVED)
        ->setOrder('created_at', 'DESC');
    ?>
    <?php if($currCat->getLevel() == '2'):?>
    <div itemscope itemtype="http://data-vocabulary.org/Breadcrumb" style="display:none;">
        <a href="<?php echo $currCat->getUrl(); ?>" itemprop="url">
            <span itemprop="title"><?php echo $currCat->getName();?></span>
        </a>
    </div>
<?php elseif($currCat->getLevel() == '3'):?>
    <div style="display:none;" >
        <?php $parentcategory = Mage::getModel('catalog/category')->load($currCat->getParentId()); ?>
        <div itemscope itemtype="http://data-vocabulary.org/Breadcrumb" itemref="<?php echo $currCat->getUrlPath();?>">
            <a href="<?php echo $parentcategory->getUrl(); ?>" itemprop="url">
                <span itemprop="title"><?php echo $parentcategory->getName(); ?></span>
            </a> ›
        </div>
        <div id="<?php echo $currCat->getUrlPath();?>" itemscope itemtype="http://data-vocabulary.org/Breadcrumb" itemprop="child">
            <a href="<?php echo $currCat->getUrl(); ?>" itemprop="url">
                <span itemprop="title"><?php echo $currCat->getName();?></span>
            </a>
        </div>
    </div>
<?php elseif($currCat->getLevel() == '4'):?>
    <div style="display:none;" >
        <?php
        $parentcategory = Mage::getModel('catalog/category')->load($currCat->getParentId());
        $parentparentcategory = Mage::getModel('catalog/category')->load($parentcategory->getParentId())
        ?>
        <div itemscope itemtype="http://data-vocabulary.org/Breadcrumb" itemref="<?php echo $parentcategory->getUrlPath();?>">
            <a href="<?php echo $parentparentcategory->getUrl(); ?>" itemprop="url">
                <span itemprop="title"><?php echo $parentparentcategory->getName(); ?></span>
            </a> ›
        </div>
        <div id="<?php echo $parentcategory->getUrlPath(); ?>" itemscope itemtype="http://data-vocabulary.org/Breadcrumb" itemref="<?php echo $currCat->getUrlPath();?>" itemprop="child">
            <a href="<?php echo $parentcategory->getUrl(); ?>" itemprop="url">
                <span itemprop="title"><?php echo $parentcategory->getName(); ?></span>
            </a> ›
        </div>
        <div id="<?php echo $currCat->getUrlPath();?>" itemscope itemtype="http://data-vocabulary.org/Breadcrumb" itemprop="child">
            <a href="<?php echo $currCat->getUrl(); ?>" itemprop="url">
                <span itemprop="title"><?php echo $currCat->getName();?></span>
            </a>
        </div>
    </div>
<?php endif;?>

    <div itemscope itemtype="http://data-vocabulary.org/Review-aggregate" style="display:none;">
        <h3>
            <span itemprop="itemreviewed"><?php echo $currCat->getName();?></span>
        </h3>
        <div>
            <div>
                <span itemprop="rating" itemscope="" itemtype="http://data-vocabulary.org/Rating">
                    <span itemprop="average">4.8</span>/<span itemprop="best">5</span>
                </span>
            </div>
            <span class="reviewcount"><span itemprop="votes"><?php echo count($review1) ;?></span> Reviews</span>
        </div>
    </div>
<?php endif; ?>















<?php echo $this->getLayout()->createBlock('catalog/product_list_toolbar')
    ->setTemplate('catalog/product/list/sort.phtml')
    ->setName('sort')
    ->toHtml(); ?>


<?php if(!$_productCollection->count()): ?>

    <p class="note-msg M5"><?php echo $this->__('There are no products matching the selection.') ?></p>

<?php else: ?>


    <div class="category-products dress_list">
        <?php $_collectionSize = $_productCollection->count() ?>
        <?php $_columnCount = 4; ?>




        <?php
            $i=0;

            foreach ($_productCollection as $_product):

                ?>
            <?php if ($i++%$_columnCount==0): ?>
            <ul class="products-grid">
            <?php endif ?>
                <li style="width:<?php echo 100/$_columnCount?>%" class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">


                    <div class="item_deatil">

                        <a href="<?php echo $_product->getProductUrl() ?>"
                           title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"
                           class="product-image"
                           style="background-image:url(<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(333,444); ?>);"
                           data-small_image="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(333,444); ?>"
                            >
                            <?php
                            if($_product->getMediaGalleryImages()){
                                foreach($_product->getMediaGalleryImages() as $GMI){
                                    if( $_product->getSmallImage() != $GMI->getFile() ){
                            ?>
                                        <img src="<?php echo $this->helper('catalog/image')->init($_product, 'image',$GMI->getFile())->resize(333,444);?>"/>
                            <?php
                                        break;
                                    }
                                }
                            }
                            ?>

                        </a>


                        <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>


                        <?php if($_product->getRatingSummary()): ?>
                            <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                        <?php endif; ?>


                        <?php echo $this->getPriceHtml($_product, true) ?>




                    </div>



                </li>
            <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
            </ul>
            <?php endif ?>
        <?php endforeach ?>

        <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
        

        <div class="toolbar-bottom">
            <?php echo $this->getToolbarHtml() ?>
        </div>
    </div>


<?php endif; ?>

<script>
    jQuery(document).ready(function($){

        $("a[data-small_image]").mouseover(function(){
            if($(this).find("img").length>0){
                $(this).css("background-image","url("+ $(this).find("img").prop("src") +")");
            }
        });

        $("a[data-small_image]").mouseout(function(){
            if($(this).find("img").length>0){
                $(this).css("background-image","url("+ $(this).data('small_image')+")");
            }
        });

    });
</script>