<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>

<!-- Structured Data-->
<?php
$productid=$_product->getId();
$table= Mage::getSingleton('core/resource')->getTableName('review_entity_summary');
$storeid= Mage::app()->getStore()->getStoreId();
$read=Mage::getSingleton('core/resource')->getConnection('core_read');
$sql="select * from `".$table."` where `entity_pk_value`=".$productid." and `store_id`=".$storeid;
$result=$read->fetchAll($sql);
if($result){
    $rating_summary=$result[0]['rating_summary']*0.05;
    $rating_summary=number_format($rating_summary,1);
    $rating_count = $result[0]['reviews_count'];
}
?>
<div itemscope itemtype="http://schema.org/Product" style="display:none;">
    <span itemprop="name"><?php echo $_product->getName()?></span>
    <img itemprop="image" src="<?php echo $this->helper('catalog/image')->init($_product, 'image')->resize(265); ?>" alt="<?php echo $_product->getName()?>" />
    <span itemprop="description"><?php echo $_product->getDescription(); ?></span>
    Product #: <span itemprop="sku"><?php echo  $_product->getSku(); ?></span>
    <?php if($rating_count):?>
    <span itemprop="aggregateRating" itemscope itemtype="http://schema.org/AggregateRating">
        <span itemprop="ratingValue"><?php echo $rating_summary; ?></span> stars, based on <span itemprop="reviewCount"><?php echo $rating_count;?></span> reviews
    </span>
    <?php endif;?>

    <span itemprop="offers" itemscope itemtype="http://schema.org/Offer">
        Regular price: <?php echo $_product->getPrice();?>
        <meta itemprop="priceCurrency" content="USD" />
        <?php if($_product->getSpecialPrice()):?>
            $<span itemprop="price"><?php echo $_product->getSpecialPrice();?></span>
        <?php else:?>
            $<span itemprop="price"><?php echo $_product->getPrice();?></span>
        <?php endif;?>
        Available from: <span itemprop="seller">Iislambridal.com</span>
        <?php if($_product->getIsInStock()):?>
            <link itemprop="availability" href="http://schema.org/InStock"/>In stock! Order now!
        <?php endif;?>
    </span>
</div>


<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>

<div id="messages_product_view"><?php echo $this->getMessagesBlock()->toHtml() ?></div>


<div class="product-view">

    <div class="product-essential">
        <form action="<?php echo $this->getSubmitUrl($_product, array('_secure' => $this->_isSecure())) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
            <?php echo $this->getBlockHtml('formkey') ?>
            <div class="no-display">
                <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
                <input type="hidden" name="related_product" id="related-products-field" value="" />
            </div>

            <div class="product-img-box">
                <?php echo $this->getChildHtml('media') ?>
            </div>

            <div class="product-shop">
                <div class="product-name">
                    <h2><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h2>
                </div>

                <div class="commont">
                    <?php echo $this->getReviewsSummaryHtml($_product, false, true)?>
                    <div class="ask-a-question"> |&nbsp; <a href="#askaquestion">Ask a question</a></div>
                    <br/>
                    <a class="share-reviews" href="<?php echo $this->getUrl('customers-feedback-gallery');?>">&gt;&gt;Share Reviews or Photos to Get $15 off Coupon</a>
                </div>



                <div class="product_price">
                    <?php echo $this->getPriceHtml($_product) ?>
                </div>


                <?php if ($_product->getShortDescription()):?>
                    <div class="short-description">
                        <h2><?php echo $this->__('Quick Overview') ?></h2>
                        <div class="std"><?php echo $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description') ?></div>
                    </div>
                <?php endif;?>

                <?php if ($_product->isSaleable() && $this->hasOptions()):?>
                    <?php echo $this->getChildChildHtml('container1', '', true, true) ?>
                <?php endif;?>

                <?php if (!$this->hasOptions()):?>
                    <div class="add-to-box">
                        <?php if($_product->isSaleable()): ?>
                            <?php echo $this->getChildHtml('addtocart') ?>
                            <?php if( $this->helper('wishlist')->isAllow() || $_compareUrl=$this->helper('catalog/product_compare')->getAddUrl($_product)): ?>
                                <span class="or"><?php echo $this->__('OR') ?></span>
                            <?php endif; ?>
                        <?php endif; ?>
                        <?php echo $this->getChildHtml('addto') ?>
                    </div>
                    <?php echo $this->getChildHtml('extra_buttons') ?>
                <?php elseif (!$_product->isSaleable()): ?>
                    <div class="add-to-box">
                        <?php echo $this->getChildHtml('addto') ?>
                    </div>
                <?php endif; ?>



                <div>
                    <?php //echo $this->getChildHtml('alert_urls') ?>
                    <?php //echo $this->getChildHtml('product_type_data') ?>
                    <?php //echo $this->getTierPriceHtml() ?>
                    <?php //echo $this->getChildHtml('extrahint') ?>
                    <?php //echo $this->getChildHtml('other');?>
                </div>


            </div>



            <div class="clearer"></div>
            <?php if ($_product->isSaleable() && $this->hasOptions()):?>
                <?php echo $this->getChildChildHtml('container2', '', true, true) ?>
            <?php endif;?>
        </form>
        <script type="text/javascript">
            //<![CDATA[
                var productAddToCartForm = new VarienForm('product_addtocart_form');
                productAddToCartForm.submit = function(button, url) {
                    if (this.validator.validate()) {
                        var form = this.form;
                        var oldUrl = form.action;

                        if (url) {
                           form.action = url;
                        }
                        var e = null;
                        try {
                            this.form.submit();
                        } catch (e) {
                        }
                        this.form.action = oldUrl;
                        if (e) {
                            throw e;
                        }

                        if (button && button != 'undefined') {
                            button.disabled = true;
                        }
                    }
                }.bind(productAddToCartForm);

                productAddToCartForm.submitLight = function(button, url){
                    if(this.validator) {
                        var nv = Validation.methods;
                        delete Validation.methods['required-entry'];
                        delete Validation.methods['validate-one-required'];
                        delete Validation.methods['validate-one-required-by-name'];
                        // Remove custom datetime validators
                        for (var methodName in Validation.methods) {
                            if (methodName.match(/^validate-datetime-.*/i)) {
                                delete Validation.methods[methodName];
                            }
                        }

                        if (this.validator.validate()) {
                            if (url) {
                                this.form.action = url;
                            }
                            this.form.submit();
                        }
                        Object.extend(Validation.methods, nv);
                    }
                }.bind(productAddToCartForm);
            //]]>
        </script>
    </div>

    <?php echo $this->getChildHtml('catalog.product.related') ?>

    <div class="new-product-collateral">

        <div class="dectits"><span>Item Details</span></div>
        <?php foreach ($this->getChildGroup('detailed_info', 'getChildHtml') as $alias => $html):?>
            <div class="box-collateral <?php echo "box-{$alias}"?>">
                <?php echo $html; ?>
            </div>
        <?php endforeach;?>
        <?php //echo $this->getChildHtml('upsell_products') ?>
        <?php //echo $this->getChildHtml('product_additional_data') ?>

        <?php /*
        <div class="dectits"><span>Size Chart</span></div>
        <div class="box-collateral box-size">
            <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('size_chart')->toHtml() ?>
        </div>

        <div class="dectits"><span>Measurement Guide</span></div>
        <div class="box-collateral box-measurement">
            <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('measurement_guide')->toHtml() ?>
        </div>
        */?>
    </div>

</div>




<?php echo $this->getChildHtml('product_viewed') ?>

<?php echo $this->getChildHtml('product_review');?>

<?php echo $this->getChildHtml('askquestions');?>