<?php if($this->getCollection()->getSize()): ?>

    <?php if($this->getLastPageNum()>1): ?>
        <?php $p_request = $this->getRequest()->getParam('p')?>

    <div class="pagination">

        <ol>

        <?php if (!$this->isFirstPage()): ?>
            <li>
                <a class="previous<?php if(!$this->getAnchorTextForPrevious()): ?> i-previous<?php endif;?>" href="<?php echo $this->getPreviousPageUrl() ?>">
                    <?php echo $this->getAnchorTextForPrevious() ?>
                </a>
            </li>
        <?php endif;?>


        <?php if ($p_request && $p_request>5): ?>
            <li><a class="first" href="<?php echo $this->getFirstPageUrl() ?>">1</a></li>
            <li><a class="previous_jump" title="" href="<?php echo $this->getPreviousJumpUrl() ?>">...</a></li>
        <?php endif?>





        <?php foreach ($this->getFramePages() as $_page): ?>
            <?php if ($this->isPageCurrent($_page)): ?>
                <li class="current"><?php echo $_page ?></li>
            <?php else: ?>
                <li><a href="<?php echo $this->getPageUrl($_page) ?>"><?php echo $_page ?></a></li>
            <?php endif;?>
        <?php endforeach;?>


        <?php if ($p_request && $p_request<$this->getLastPageNum()-3): ?>
            <li><a class="next_jump" title="" href="<?php echo $this->getNextJumpUrl() ?>">...</a></li>
            <li><a class="last" href="<?php echo $this->getLastPageUrl() ?>"><?php echo $this->getLastPageNum() ?></a></li>
        <?php endif;?>


        <?php if (!$this->isLastPage()): ?>
            <li>
                <a class="next<?php if(!$this->getAnchorTextForNext()): ?> i-next<?php endif; ?>" href="<?php echo $this->getNextPageUrl() ?>">
                    <?php echo $this->getAnchorTextForNext() ?>
                </a>
            </li>
        <?php endif;?>



        </ol>

    </div>
    <?php endif; ?>


<?php endif ?>
