<?php
$categoryId = (int) $this->getRequest()->getParam('category', false);
$category = Mage::getModel('catalog/category')
                ->setStoreId(Mage::app()->getStore()->getId())
                ->load($categoryId);
if($category->getLevel() > 2){
    $category = $category->getParentCategory();
}

$productCollection = $category
                        ->getProductCollection()
                        ->addAttributeToSelect('*')
                        ->addAttributeToFilter('status', 1)
                        ->addAttributeToFilter('visibility', 4);
foreach ($productCollection as $product) {
    $result[] = $product->getId();
}
if(count($result) > 5){
    $ourneed_key = array_rand($result,6);
}else{
    $ourneed_key = array_keys($result);
}
foreach($ourneed_key as $k){
    $ourneed[] = $result[$k];
}
?>
<?php if( count($ourneed) >0 ): ?>
    <div class="box_shadow parent_cat_related">
        <div class="category_name_bottom">
            <span>CUSTOMERS WHO BOUGHT THIS ITEM ALSO LIKE</span>
        </div>
        <div class="home_product">
            <?php foreach($productCollection as $_product):?>
                <?php if( in_array($_product->getId(),$ourneed) ):?>
                    <dl class="item">
                        <dt>
                            <a href="<?php echo $_product->getProductUrl() ?>">
                                <img width="180" height="240" alt="<?php echo $_product->getName()?>" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(240,320); ?>">
                            </a>
                        </dt>
                        <dd>
                            <p>
                                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_product->getName()?>">
                                    <?php echo $_product->getName()?>
                                </a>
                            </p>
                            <div class="home_price">
                                <span><?php echo Mage::app()->getStore()->getCurrentCurrency()->getCode();?></span>
                                <?php echo $this->getPriceHtml($_product, true) ?>
                            </div>
                        </dd>
                    </dl>
                <?php endif; ?>
            <?php endforeach; ?>
        </div>
    </div>
<?php endif ?>
