<?php
$categoryId = (int) $this->getRequest()->getParam('category', false);
$category = Mage::getModel('catalog/category')
                ->setStoreId(Mage::app()->getStore()->getId())
                ->load($categoryId);
if($category->getLevel() > 2){
    $category = $category->getParentCategory();
}

$count_cat_p = $category
    ->getProductCollection()
    ->addAttributeToSelect('*')
    ->addAttributeToFilter('status', 1)
    ->addAttributeToFilter('visibility', 4)
    ->count();
$productCollection = $category
                        ->getProductCollection()
                        ->addAttributeToSelect('*')
                        ->addAttributeToFilter('status', 1)
                        ->addAttributeToFilter('visibility', 4)
                        ->setPage(rand(1,$count_cat_p/32), 6);

?>

<?php if( count($productCollection) >0 ): ?>
    <div class="box_shadow parent_cat_related">
        <div class="category_name_bottom">
            <span>CUSTOMERS WHO BOUGHT THIS ITEM ALSO LIKE</span>
        </div>
        <div class="home_product">
            <?php foreach($productCollection as $_product):?>
                    <dl class="item">
                        <dt>
                            <a href="<?php echo $_product->getProductUrl() ?>">
                                <img alt="<?php echo $_product->getName()?>" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(240,320); ?>">
                            </a>
                        </dt>
                        <dd>
                            <p>
                                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_product->getName()?>">
                                    <?php echo $_product->getName()?>
                                </a>
                            </p>
                            <div class="home_price">
                                <span><?php echo Mage::app()->getStore()->getCurrentCurrency()->getCode();?></span>
                                <?php echo $this->getPriceHtml($_product, true) ?>
                            </div>
                        </dd>
                    </dl>
            <?php endforeach; ?>
        </div>
    </div>
<?php endif ?>
