<?php if (!Mage::registry('current_category')) return ?>

<?php
    $_categories = $this->getCurrentChildCategories();
    $_count = is_array($_categories)?count($_categories):$_categories->count();

    if(empty($_count)){
        $_categories =  Mage::getModel('catalog/category')
            ->setStoreId(Mage::app()->getStore()->getId())
            ->load( Mage::registry('current_category')->getParentId() )
            ->getChildrenCategories();
        $_count = is_array($_categories)?count($_categories):$_categories->count();
    }

    if($_count>8){
        $rand_cat = array_rand($_categories->toArray(),8);
    }
?>


<?php if($_count):?>
    <div class="box_shadow">
        <div class="category_name_bottom">
            <span><?php echo Mage::registry('current_category')->getName(); ?> Related Categories</span>
        </div>
        <div class="catalog_children">
            <ol>
                <?php foreach ($_categories as $_category): ?>
                    <?php if($_category->getIsActive() && in_array($_category->getId(),$rand_cat)  ): ?>
                        <li>
                            <a href="<?php echo $this->getCategoryUrl($_category) ?>"<?php if ($this->isCategoryActive($_category)): ?> class="current"<?php endif; ?>><?php echo $this->escapeHtml($_category->getName()) ?></a>
                        </li>
                    <?php endif; ?>
                <?php endforeach ?>
            </ol>
        </div>
    </div>


<?php endif; ?>