
<?php if (!Mage::registry('current_category')) return ?>
<?php $_categories = $this->getCurrentChildCategories() ?>
<?php $_count = is_array($_categories)?count($_categories):$_categories->count(); ?>
<?php
    if($_count):
        if($_count>8){
            $count_i = 0;
        }
?>
    <ol>
        <?php foreach ($_categories as $_category): ?>
            <?php
            if($_count>8){
                if($count_i<8){
                    $count_i++;
                }else{
                    break;
                }
            }
            ?>
            <?php if($_category->getIsActive()): ?>
                <li>
                    <a href="<?php echo $this->getCategoryUrl($_category) ?>"<?php if ($this->isCategoryActive($_category)): ?> class="current"<?php endif; ?>><?php echo $this->escapeHtml($_category->getName()) ?></a>
                </li>
            <?php endif; ?>
        <?php endforeach ?>
    </ol>
<?php endif; ?>
