
<div class="shopping_bag">

    <div class="scart_step1"></div>

    <div class="shopping_bag_title">Shopping Bag</div>

    <?php echo $this->getMessagesBlock()->toHtml() ?>

    <div class="empty_cart_div">
        <div class="empty_cart_msg">
            <h4>Your Shopping Cart is empty.</h4>
            <p>You have the power to change this! Add all wedding apparel you've been dreaming of !</p>
            <p>
                <a href="<?php echo Mage::helper('core')->quoteEscape($this->getContinueShoppingUrl()) ?>" class="bt-1-new">
                    <span>Continue Shopping</span>
                </a>
            </p>
        </div>
    </div>

</div>

