<?php if ($_products = $this->getRecentlyViewedProducts()): ?>
<div class="box_shadow">
    <div class="category_name_bottom">
        <span>Recently Viewed</span>
    </div>

    <div class="home_product owl-carousel">

         <?php foreach($_products as $_product):?>

            <dl class="item">
                <dt>
                    <a href="<?php echo $_product->getProductUrl() ?>">
                        <img width="180" height="240" alt="<?php echo $_product->getName()?>" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(240,320); ?>">
                    </a>
                </dt>
                <dd>
                    <p>
                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_product->getName()?>">
                            <?php echo $_product->getName()?>
                        </a>
                    </p>
                    <div class="home_price">
                        <span><?php echo Mage::app()->getStore()->getCurrentCurrency()->getCode();?></span>
                        <?php echo $this->getPriceHtml($_product, true) ?>
                    </div>
                </dd>
            </dl>

        <?php endforeach; ?>

    </div>

        <script>
            jQuery(document).ready(function(){
                jQuery('.home_product').each(function() {
                    if(jQuery('.item', this).length > 1) {
                        jQuery(this).owlCarousel({
                            loop: true,
                            nav: true,
                            dots:false,
                            autoWidth:true,
                            margin:15,
                            autoplay: false
                        });
                    }
                });
            });
        </script>
</div>
<?php endif; ?>
