<?php echo $this->getMessagesBlock()->toHtml() ?>

<?php
$cur_cat_name = $this->getCurrentCategory()->getName();
$cur_cat_pro_size = Mage::getSingleton('catalog/layer')->getProductCollection()->getSize();
?>


<div class="category_name_top">
    <h2><?php echo $cur_cat_name ?></h2>
    <span>(<?php echo $cur_cat_pro_size;?>)</span>


    <?php $countdowns = Mage::getModel('ibanners/group')->loadByCode('countdown')->getBannerCollection(); ?>
    <?php
        foreach($countdowns as $countdown){
            if( strtotime($countdown->getAltText()) > time()  ){
                if(  $countdown->getTitle() == $this->getCurrentCategory()->getUrlKey()  ){
                    $curr_countdown['curr'] = $countdown;
                }elseif($countdown->getTitle() == 'default' ){
                    $curr_countdown['default'] = $countdown;
                }
            }
        }
        if( isset($curr_countdown) ){
            $show_countdown = isset($curr_countdown['curr'])?$curr_countdown['curr']:$curr_countdown['default'];
        }
    ?>

    <?php if( isset($show_countdown) ):?>
        <div class="countdow">
            <div onclick="window.location.href='<?php echo $show_countdown->getUrl(); ?>'">
                <?php echo $show_countdown->getHtml();?>
                <span id="countdownie" class="PositionAbsolute"></span>
            </div>
            <script type="text/javascript">
                <?php $date_time = strtotime($show_countdown->getAltText()); ?>
                jQuery(document).ready(function(){
                    countdown('countdownie', <?php echo date("Y",$date_time)?>, <?php echo date("m",$date_time)?>, <?php echo date("d",$date_time)?>, <?php echo date("H",$date_time)?>, <?php echo date("i",$date_time)?>, <?php echo date("s",$date_time)?>);
                });
            </script>
        </div>
    <?php endif;?>






</div>


<?php echo $this->getChildHtml('catalog.layer.view') ?>


<?php echo $this->getProductListHtml() ?>




<?php if($_description=$this->getCurrentCategory()->getDescription()): ?>
    <div class="box_shadow">
        <div class="category_name_bottom">
            <span><?php echo $cur_cat_name ?></span>
            <span>(<?php echo $cur_cat_pro_size;?>)</span>
        </div>

        <div class="cur_category_description">
            <?php echo $_description ?>
            <div class="see" style="display:none;">
                <span id="see_con" class="see_more">See more</span>
                <span>&gt;&gt;</span>
            </div>
        </div>
        <script>
            jQuery(document).ready(function(){
                if(jQuery(".cur_category_description")[0].clientHeight == 100){
                    jQuery(".see").show();
                }
                jQuery('.cur_category_description').on('click','.see',function(){
                    if(jQuery("#see_con").hasClass('see_more')){
                        jQuery(".cur_category_description").css('max-height',"none");
                        jQuery("#see_con").removeClass('see_more').addClass('see_less').html('See less');
                    }else{
                        jQuery(".cur_category_description").css('max-height',"100px");
                        jQuery("#see_con").removeClass('see_less').addClass('see_more').html('See more');
                    }
                });
            });
        </script>
    </div>
<?php endif; ?>




<?php
    $_reviewsCollection = Mage::getModel('review/review')->getCollection()
        ->addStoreFilter(Mage::app()->getStore()->getId())
        ->addStatusFilter(Mage_Review_Model_Review::STATUS_APPROVED)
//        ->addFieldToFilter(
//            array(
//                array('attribute'=>'detailc','eq'=>'reviewimage1'),
//                array('attribute'=>'detailc','eq'=>'reviewimage2'),
//                array('attribute'=>'detailc','eq'=>'reviewimage3'),
//                array('attribute'=>'detailc','eq'=>'reviewimage4'),
//                array('attribute'=>'detailc','eq'=>'reviewimage5'),
//            ),
//            array(
//                array(  array('notnull' => true) ),
//                array(  array('notnull' => true) ),
//                array(  array('notnull' => true) ),
//                array(  array('notnull' => true) ),
//                array(  array('notnull' => true) ),
//            )
//        )
        ->getSelect()
        ->joinleft( array('cp'=> 'catalog_category_product'), 'cp.product_id = main_table.entity_pk_value')
        ->where("main_table.status_id=1  and cp.`category_id`='".$this->getCurrentCategory()->getId()."'")
        ->order("main_table.created_at DESC")
        ->limit(10);

    $results = Mage::getSingleton('core/resource')->getConnection('core_read')->fetchAll($_reviewsCollection);
?>
<?php if(count($results)):?>
    <div class="box_shadow">
        <div class="category_name_bottom">
            <h3>Most Helpful Reviews about <?php echo $cur_cat_name ?></h3>
            <span>(<?php
                $review_count_sql = Mage::getModel('review/review')->getCollection()
                    ->getSelect()
                    ->columns(array(
                            'review_count' => 'count(cp.category_id)')
                    )
                    ->joinleft( array('cp'=> 'catalog_category_product'), 'cp.product_id = main_table.entity_pk_value')
                    ->where("main_table.status_id=1  and cp.`category_id`='".$this->getCurrentCategory()->getId()."'");

                $review_count = Mage::getSingleton('core/resource')->getConnection('core_read')->fetchAll($review_count_sql);
                foreach ($review_count as $row){echo $row['review_count'];break;}
                ?>)</span>

        </div>
        <div class="last_review">
            <?php foreach ($results as $review):?>
                <?php if( $review['entity_pk_value'] ):?>

                    <div class="review_row">
                        <?php $review_product = Mage::getModel('catalog/product')->setStoreId(Mage::app()->getStore()->getId())->load($review['entity_pk_value']);?>
                        <a class="p_image" href="<?php echo $review_product->getProductUrl()?>">
                            <img src="<?php echo Mage::helper('catalog/image')->init($review_product, 'image')->resize(333,444);?>"/>
                        </a>



                        <div class="review_d">
                            <?php
                            $votesCollection = Mage::getModel('rating/rating_option_vote')
                                ->getResourceCollection()
                                ->setReviewFilter($review['review_id'])
                                ->setStoreFilter(Mage::app()->getStore()->getId())
                                ->addRatingInfo(Mage::app()->getStore()->getId())
                                ->load();
                            ?>
                            <?php if (count($votesCollection)): ?>
                                <?php $percent = 0;foreach ($votesCollection as $_vote): $percent += $_vote->getPercent(); ?><?php endforeach; ?>
                                <div class="rating-box">
                                    <div class="rating" style="width:<?php echo $percent/3 ?>%;"></div>
                                </div>
                            <?php endif; ?>
                            <div class="review_info_1"><?php echo $this->escapeHtml($review['title']) ?></div>
                            <div class="review_info_2">By <?php echo $this->escapeHtml($review['nickname']);?>, Posted on <?php echo $this->formatDate($review['created_at']);?></div>
                            <div class="review_info_3"><?php echo $review['detail']?></div>
                            <div class="review_info_4">
                                <?php 
                                    if($review['reviewimage1']){
                                        echo '<img src="'.Mage::getBaseUrl("media").'reviewimages'.$review['reviewimage1'].'"/>';
                                    }
                                    if($review['reviewimage2']){
                                        echo '<img src="'.Mage::getBaseUrl("media").'reviewimages'.$review['reviewimage2'].'"/>';
                                    }
                                    if($review['reviewimage3']){
                                        echo '<img src="'.Mage::getBaseUrl("media").'reviewimages'.$review['reviewimage3'].'"/>';
                                    }
                                    if($review['reviewimage4']){
                                        echo '<img src="'.Mage::getBaseUrl("media").'reviewimages'.$review['reviewimage4'].'"/>';
                                    }
                                    if($review['reviewimage5']){
                                        echo '<img src="'.Mage::getBaseUrl("media").'reviewimages'.$review['reviewimage5'].'"/>';
                                    }
                                ?>  
                            </div>
                            
                        </div>
                    </div>
                <?php endif;?>
            <?php endforeach;?>
        </div>
    </div>

<?php endif;?>





















<?php echo $this->getChildHtml('catalog_children') ?>


<?php echo $this->getChildHtml('product_viewed') ?>




