<?php echo $this->getMessagesBlock()->toHtml() ?>

<?php
$cur_cat_name = $this->getCurrentCategory()->getName();
$cur_cat_pro_size = Mage::getSingleton('catalog/layer')->getProductCollection()->getSize();
?>


<div class="category_name_top">
    <span><?php echo $cur_cat_name ?></span>
    <span>(<?php echo $cur_cat_pro_size;?>)</span>


    <?php $countdowns = Mage::getModel('ibanners/group')->loadByCode('countdown')->getBannerCollection(); ?>
    <?php
        foreach($countdowns as $countdown){
            if( strtotime($countdown->getAltText()) > time()  ){
                if(  $countdown->getTitle() == $this->getCurrentCategory()->getUrlKey()  ){
                    $curr_countdown['curr'] = $countdown;
                }elseif($countdown->getTitle() == 'default' ){
                    $curr_countdown['default'] = $countdown;
                }
            }
        }
        if( isset($curr_countdown) ){
            $show_countdown = isset($curr_countdown['curr'])?$curr_countdown['curr']:$curr_countdown['default'];
        }
    ?>

    <?php if( isset($show_countdown) ):?>
        <div class="countdow">
            <div onclick="window.location.href='<?php echo $show_countdown->getUrl(); ?>'">
                <?php echo $show_countdown->getHtml();?>
                <span id="countdownie" class="PositionAbsolute"></span>
            </div>
            <script type="text/javascript">
                function countdown(id,theyear,themonth,theday,thehour,themin,thesec){
                    id=id;
                    yr=theyear;
                    mo=themonth;
                    da=theday;
                    ho=thehour;
                    mi=themin;
                    se=thesec;
                    var montharray=new Array("Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec");
                    var today=new Date();
                    var todayy=today.getYear();
                    if (todayy < 1000)
                        todayy+=1900;
                    var todaym=today.getMonth();
                    var todayd=today.getDate();
                    var todayh=today.getHours();
                    var todaymin=today.getMinutes();
                    var todaysec=today.getSeconds();
                    var todaystring=montharray[todaym]+" "+todayd+", "+todayy+" "+todayh+":"+todaymin+":"+todaysec;
                    futurestring=montharray[mo-1]+" "+da+", "+yr+" "+ho+":"+mi+":"+se;
                    dd=Date.parse(futurestring)-Date.parse(todaystring);
                    dday=Math.floor(dd/(60*60*1000*24)*1);
                    dhour=Math.floor((dd%(60*60*1000*24))/(60*60*1000)*1);

                    if(0<dhour && dhour<10){dhour="0"+dhour;}
                    dmin=Math.floor(((dd%(60*60*1000*24))%(60*60*1000))/(60*1000)*1);
                    if(0<dmin && dmin<10){dmin="0"+dmin;}
                    dsec=Math.floor((((dd%(60*60*1000*24))%(60*60*1000))%(60*1000))/1000*1);
                    if(0<dsec && dsec<10){dsec = "0"+dsec;}



                    if(dday<=0 && dhour<=0&&dmin<=0&&dsec<=1&&todayd==da){
                        document.getElementById(id).innerHTML='';
                        return;
                    }else if (dday<=-1){
                        document.getElementById(id).innerHTML="";
                        return;
                    }else{
                        var countdown_html = '';
                        if(dday>0){
                            countdown_html = '<span class="dday">'+dday+'</span>';
                            countdown_html +='<span class="text_day">D</span>';
                        }
                        countdown_html  +=  '<span class="dhour">'+dhour+'</span>'+
                                            '<span class="dmin">'+dmin+'</span>'+
                                            '<span class="dsec">'+dsec+'</span>';
                        document.getElementById(id).innerHTML = countdown_html;
                        setTimeout(function(){countdown(id,yr,mo,da,ho,mi,se)},1000);
                    }
                }
                <?php $date_time = strtotime($show_countdown->getAltText()); ?>
                countdown('countdownie',
                    <?php echo date("Y",$date_time)?>,
                    <?php echo date("m",$date_time)?>,
                    <?php echo date("d",$date_time)?>,
                    <?php echo date("H",$date_time)?>,
                    <?php echo date("i",$date_time)?>,
                    <?php echo date("s",$date_time)?>);
            </script>
        </div>
    <?php endif;?>






</div>


<?php echo $this->getChildHtml('mana.catalog.leftnav') ?>


<?php echo $this->getProductListHtml() ?>




<?php if($_description=$this->getCurrentCategory()->getDescription()): ?>
    <div class="box_shadow">
        <div class="category_name_bottom">
            <span><?php echo $cur_cat_name ?></span>
            <span>(<?php echo $cur_cat_pro_size;?>)</span>
        </div>

        <div class="cur_category_description">
            <?php echo $_description ?>
            <div class="see" style="display:none;">
                <span id="see_con" class="see_more">See more</span>
                <span>&gt;&gt;</span>
            </div>
        </div>
        <script>
            jQuery(document).ready(function(){
                if(jQuery(".cur_category_description")[0].clientHeight == 100){
                    jQuery(".see").show();
                }
                jQuery('.cur_category_description').on('click','.see',function(){
                    if(jQuery("#see_con").hasClass('see_more')){
                        jQuery(".cur_category_description").css('max-height',"none");
                        jQuery("#see_con").removeClass('see_more').addClass('see_less').html('See less');
                    }else{
                        jQuery(".cur_category_description").css('max-height',"100px");
                        jQuery("#see_con").removeClass('see_less').addClass('see_more').html('See more');
                    }
                });
            });
        </script>
    </div>
<?php endif; ?>




    <?php
    $_reviewsCollection = Mage::getModel('review/review')->getCollection()
        ->addStoreFilter(Mage::app()->getStore()->getId())
        ->addStatusFilter(Mage_Review_Model_Review::STATUS_APPROVED)
        ->addFieldToFilter(
            array(
                array('attribute'=>'detailc','eq'=>'reviewimage1'),
                array('attribute'=>'detailc','eq'=>'reviewimage2'),
                array('attribute'=>'detailc','eq'=>'reviewimage3'),
                array('attribute'=>'detailc','eq'=>'reviewimage4'),
                array('attribute'=>'detailc','eq'=>'reviewimage5'),
            ),
            array(
                array(  array('notnull' => true) ),
                array(  array('notnull' => true) ),
                array(  array('notnull' => true) ),
                array(  array('notnull' => true) ),
                array(  array('notnull' => true) ),
            )
        )
        ->setDateOrder();
    $_reviews_items =  $_reviewsCollection->getItems();
    ?>
    <?php if(count($_reviews_items) > 0): ?>
        <div class="box_shadow">
            <div class="category_name_bottom">
                <span><?php echo $cur_cat_name ?> reviews </span>
                <span>(<?php echo count($_reviews_items);?>)</span>
            </div>
            <div class="user_photos">
                <div class="photos_title">User Photos</div>
                <div class="home_review owl-carousel">
                    <?php foreach($_reviews_items as $review): ?>
                        <a class="item" href="<?php 
                                                                echo Mage::getModel('catalog/product')
                                                                ->setStoreId(Mage::app()->getStore()->getId())
                                                                ->load($review->getEntityPkValue())
                                                                ->getProductUrl();
                                                                    ?>#review">
                            <?php if(  $review->getReviewimage1()  ):?>
                                <span style="background-image:url(<?php echo Mage::getBaseUrl("media").'reviewimages/'.$review->getReviewimage1();?>);"></span>
                            <?php elseif(  $review->getReviewimage2()  ): ?>
                                <span style="background-image:url(<?php echo Mage::getBaseUrl("media").'reviewimages/'.$review->getReviewimage2();?>);"></span>
                            <?php elseif(  $review->getReviewimage3()  ): ?>
                                <span style="background-image:url(<?php echo Mage::getBaseUrl("media").'reviewimages/'.$review->getReviewimage3();?>);"></span>
                            <?php elseif(  $review->getReviewimage4()  ): ?>
                                <span style="background-image:url(<?php echo Mage::getBaseUrl("media").'reviewimages/'.$review->getReviewimage4();?>);"></span>
                            <?php elseif(  $review->getReviewimage5()  ): ?>
                                <span style="background-image:url(<?php echo Mage::getBaseUrl("media").'reviewimages/'.$review->getReviewimage5();?>);"></span>
                            <?php endif;?>
                        </a>
                    <?php endforeach; ?>
                </div>
                <script>
                    jQuery(document).ready(function(){
                        jQuery('.home_review').each(function() {
                            if(jQuery('.item', this).length > 1) {
                                jQuery(this).owlCarousel({
                                    loop: true,
                                    nav: true,
                                    dots: false,
                                    autoWidth:true,
                                    margin:10,
                                    autoplay: false
                                });
                            }
                        });
                    });
                </script>
            </div>
        </div>
    <?php endif; ?>





<?php echo $this->getChildHtml('catalog_children') ?>


<?php echo $this->getChildHtml('product_viewed') ?>




