<?php if($crumbs && is_array($crumbs)): ?>
<div class="breadcrumbs">
    <ul>
        <?php $i = count($crumbs); $j=0;?>
        <?php foreach($crumbs as $_crumbName=>$_crumbInfo): ?>

            <li class="<?php echo $_crumbName ?> <?php if($_crumbInfo['last']){ echo 'last';} ?>" 
                style="
                z-index:<?php echo $i; $i--;?>;
                left:<?php echo (-8*$j);$j++;?>px;
                ">

            <?php if($_crumbInfo['link']): ?>

                <a href="<?php echo $_crumbInfo['link'] ?>" title="<?php echo $this->escapeHtml($_crumbInfo['title']) ?>"><?php echo $this->escapeHtml($_crumbInfo['label']) ?></a>

            <?php elseif($_crumbInfo['last']): ?>

                <strong style="left:<?php echo (-8*$j);$j++;?>px;"><?php echo $this->escapeHtml($_crumbInfo['label']) ?></strong>

            <?php else: ?>

                <?php echo $this->escapeHtml($_crumbInfo['label']) ?>

            <?php endif; ?>


            </li>

        <?php endforeach; ?>
    </ul>

    <div class="share">
        <span>Share</span>
        <?php if($_SERVER['HTTP_HOST'] != '127.0.0.1'):?>
            <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-574c55c4ca60398e"></script>
        <?php endif;?>
        <div class="addthis_sharing_toolbox"></div>
    </div>
</div>
<?php endif; ?>
