<footer>
    <div class="footer_contant">
        <div class="join_us">
            <?php echo Mage::getModel('core/variable')->loadByCode('Community_link')->getValue('html');?>
        </div>
        <div class="customer_help">
            <?php echo Mage::getModel('core/variable')->loadByCode('footer_customer_help_1')->getValue('html');?>
            <?php echo Mage::getModel('core/variable')->loadByCode('footer_customer_help_2')->getValue('html');?>
            <?php echo Mage::getModel('core/variable')->loadByCode('footer_customer_help_3')->getValue('html');?>
            <?php echo Mage::getModel('core/variable')->loadByCode('footer_customer_help_4')->getValue('html');?>
        </div>
        <div class="payments">
            <span class="banks">visa, master card, maestro, carte blue</span>
            <a href="javascript:void(0);" target="_top" class="paypal">paypal</a>
            <a href="javascript:void(0);" title="wholesale Paypal Verify " class="paypalVerified">paypal verified</a>
            <span class="boleto-logo-footer"></span>
            <span class="westernUnion">western union</span>
            <span class="norton-logo"></span>
            <span class="delivery">dhl ups ems</span>
        </div>
        <div class="copyright"><address><?php echo $this->getCopyright() ?></address></div>
    </div>
</footer>

<div id="gotopbtn" style="display:none;"><a href="#"><span></span>Back To Top</a></div>
<script type="text/javascript">
    jQuery(function($){
        $("#gotopbtn").hide();
        $(function () {
            $(window).scroll(function(){
                if ($(window).scrollTop()>100){
                    $("#gotopbtn").show();
                }
                else
                {
                    $("#gotopbtn").hide();
                }
            });
            //back to top
            $("#gotopbtn").click(function(){
                $('body,html').animate({scrollTop:0},1000);
                return false;
            });
        });
    });
</script>