<footer>
    <div class="footer_contant">
        <div class="join_us">
            <h2>Join our community</h2>
            <ul>
                <li class="mini-facebook"><a href=""></a></li>
                <li class="mini-instagram"><a href=""></a></li>
                <li class="mini-pinterest"><a href=""></a></li>
                <li class="mini-youtube"><a href=""></a></li>
                <li class="mini-twitter"><a href=""></a></li>
                <li class="mini-tumbler"><a href=""></a></li>
                <li class="mini-blog"><a href=""></a></li>
                <li class="mini-vk"><a href=""></a></li>
            </ul>
        </div>
        <div class="customer_help">
            <dl>
                <dt>CUSTOMER GUIDANCE</dt>
                <dd><a rel="nofollow" href="<?php echo $this->getUrl('login-problems')?>">Login Problems</a></dd>
                <dd><a rel="nofollow" href="<?php echo $this->getUrl('trace-your-order')?>">Trace Your Order</a></dd>
                <dd><a rel="nofollow" href="<?php echo $this->getUrl('payment-methods')?>">Payment Methods</a></dd>
            </dl>
            <dl>
                <dt>PRODUCT INFO</dt>
                <dd><a rel="nofollow" href="<?php echo $this->getUrl('size-chart')?>">Size Chart</a></dd>
                <dd><a rel="nofollow" href="<?php echo $this->getUrl('color-chart')?>">Color Chart</a></dd>
                <dd><a rel="nofollow" href="<?php echo $this->getUrl('measurement')?>">Measurement</a></dd>
            </dl>
            <dl>
                <dt>SHIPPING & DELIVERY</dt>
                <dd><a rel="nofollow" href="<?php echo $this->getUrl('processing-shipping-time')?>">Processing & Shipping Time</a></dd>
                <dd><a rel="nofollow" href="<?php echo $this->getUrl('shipping-methods')?>">Shipping Methods</a></dd>
                <dd><a rel="nofollow" href="<?php echo $this->getUrl('customs-and-import-tax')?>">Customs and Import Tax</a></dd>
            </dl>
            <dl>
                <dt>Refund & return</dt>
                <dd><a rel="nofollow" href="<?php echo $this->getUrl('return-and-exchange-policy')?>">Return and Exchange Policy</a></dd>
                <dd><a rel="nofollow" href="<?php echo $this->getUrl('cancel-order')?>">Cancel Order</a></dd>
                <dd><a rel="nofollow" href="<?php echo $this->getUrl('contact-us')?>">Contact US</a></dd>
                <dd><a rel="nofollow" href="<?php echo $this->getUrl('faq')?>">FAQ</a></dd>
                <dd><a rel="nofollow" href="<?php echo $this->getUrl('where-we-ship-to')?>">Where we ship to</a></dd>
            </dl>
        </div>
        <div class="payments">
            <span class="banks">visa, master card, maestro, carte blue</span>
            <a href="javascript:void(0);" target="_top" class="paypal">paypal</a>
            <a href="javascript:void(0);" title="wholesale Paypal Verify " class="paypalVerified">paypal verified</a>
            <span class="boleto-logo-footer"></span>
            <span class="westernUnion">western union</span>
            <span class="norton-logo"></span>
            <span class="delivery">dhl ups ems</span>
        </div>
        <div class="copyright"><address><?php echo $this->getCopyright() ?></address></div>
    </div>
</footer>

<div id="gotopbtn" style="display:none;"><a href="#"><span></span>Back To Top</a></div>
<script type="text/javascript">
    jQuery(function($){
        $("#gotopbtn").hide();
        $(function () {
            $(window).scroll(function(){
                if ($(window).scrollTop()>100){
                    $("#gotopbtn").show();
                }
                else
                {
                    $("#gotopbtn").hide();
                }
            });
            //back to top
            $("#gotopbtn").click(function(){
                $('body,html').animate({scrollTop:0},1000);
                return false;
            });
        });
    });
</script>