<header>
    <div class="new_header">
        <div class="header_top">
            <?php echo $this->getChildHtml('top.currency') ?>
            <div class="welcome_message">
                <div id="demo">
                    <div id="demo1">
                        <?php $top_promotion = Mage::getModel('ibanners/group')->loadByCode('top_center_promotion')->getBannerCollection();?>
                        <?php foreach($top_promotion as $promotion):?>
                            <?php echo $promotion->getHtml();?>
                        <?php endforeach;?>
                    </div>
                    <div id="demo2"></div>
                </div>
                <script>
                    //头部－上下滚动显示欢迎语和店内活动。
                    function Marquee(){
                        if(demo2.offsetTop-demo.scrollTop<=0)
                            demo.scrollTop-=demo1.offsetHeight
                        else{
                            demo.scrollTop++
                        }
                    }
                    var speed=100;
                    demo2.innerHTML=demo1.innerHTML
                    var MyMar=setInterval(Marquee,speed)
                    demo.onmouseover=function() {clearInterval(MyMar)}
                    demo.onmouseout=function() {MyMar=setInterval(Marquee,speed)}
                </script>
            </div>
            <div class="top_nav">
                <?php if(Mage::getSingleton('customer/session')->isLoggedIn()):?>
                    <a rel="nofollow" href="<?php echo $this->getUrl('customer/account')?>">My Account</a>
                    &nbsp;&nbsp;|&nbsp;&nbsp;
                    <a rel="nofollow" href="<?php echo $this->getUrl('customer/account/logout')?>">Log Out</a>
                <?php else:?>
                    <a rel="nofollow" href="<?php echo $this->getUrl('customer/account')?>">Join Free</a>
                    or
                    <a rel="nofollow" href="<?php echo $this->getUrl('customer/account')?>">Log in</a>
                <?php endif;?>
                &nbsp;&nbsp;|&nbsp;&nbsp;
                <a rel="nofollow" href="<?php echo $this->getUrl('help')?>">Help</a>
                &nbsp;&nbsp;|&nbsp;&nbsp;
                <a class="CustomerService_a" href="javascript:;">Customer Service</a>
                <div class="CustomerService">
                    <div class="and"></div>
                    <p>
                        <span></span>
                        <a rel="nofollow" href="mailto:<?php echo Mage::getStoreConfig('trans_email/ident_general/email');?>">
                            Email: <?php echo Mage::getStoreConfig('trans_email/ident_general/email');?>
                        </a>
                    </p>
                    <script>
                        jQuery(document).ready(function($){
                            $(".CustomerService_a , .CustomerService").hover(
                                function(){
                                    $(".CustomerService").show();
                                },
                                function(){
                                    $(".CustomerService").hide();
                                }
                            );
                        });
                    </script>
                </div>
            </div>
        </div>
        <div class="header_content">
            <div class="header_logo">
                <?php if ($this->getIsHomePage()):?>
                    <h1 class="logo">
                        <a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo">
                            <img src="<?php echo $this->getUrl('') ?>/skin/frontend/pc/default/images/logo.png" alt="<?php echo $this->getLogoAlt() ?>" />
                        </a>
                    </h1>
                <?php else:?>
                    <a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo">
                        <img src="<?php echo $this->getUrl('') ?>/skin/frontend/pc/default/images/logo.png" alt="<?php echo $this->getLogoAlt() ?>" />
                    </a>
                <?php endif?>
            </div>
            <div class="header_search"><?php echo $this->getChildHtml('topSearch') ?></div>
            <div class="header_cart">
                <a href="<?php echo $this->getUrl('wishlist')?>" class="favor"><em>&nbsp;</em></a>
                <?php echo $this->getChildHtml('top.cart') ?>
            </div>
        </div>
        <div class="header_menu">
            <ul>
                <li class="home"><a href="<?php echo $this->getUrl();?>">home</a></li>
                <?php
                $menu_tops = Mage::getModel('catalog/category')
                    ->setStoreId(Mage::app()->getStore()->getId())
                    ->load(2)
                    ->getChildrenCategories();
                ?>
                <?php foreach($menu_tops as $menu):?>
                    <li>
                        <a href="<?php echo $menu->getUrl();?>"><?php echo $menu->getName();?></a>
                        <div class="level2">
                            <?php echo $this->getLayout()->createBlock('cms/block')
                                ->setBlockId($menu->getUrlKey())
                                ->toHtml() ?>
                        </div>
                    </li>
                <?php endforeach;?>
            </ul>
            <script>
                jQuery(".header_menu ul li").on('mouseover',function(){
                    var level2 = jQuery(this).find('.level2');
                    level2.show();
                    if(jQuery(this).index()<3){
                        return false;
                    }
                    if (document.documentElement && document.documentElement.clientWidth){
                        winWidth = document.documentElement.clientWidth;
                    }

                    var li_offset = jQuery(this).offset();
                    var li_left = li_offset.left;
                    var li_right = winWidth - li_left - jQuery(this)[0].clientWidth;

                    var offset = level2.offset();
                    var level2_left = offset.left;
                    var level2_right = winWidth - li_left - level2[0].clientWidth;

                    if(li_left<100 ){
                        level2.css({left:'0',right:'auto'});
                    }else{
                        if(level2_right>0){
                            level2.css({left:'-100px',right:'auto'});
                        }else{
                            if(level2[0].clientWidth - level2_right*(-1) > 200 ){
                                level2.css({left:'auto',right:'-100px'});
                            }else{
                                level2.css({left:'auto',right:'0'});
                            }
                        }
                    }
                });

                jQuery(".header_menu ul li").on('mouseout',function(){
                    jQuery(this).find('.level2').hide();
                });
            </script>
        </div>
    </div>
</header>



<?php /*倒计时广告**/ ?>
<?php if($countdowns = Mage::getModel('ibanners/group')->loadByCode('header_countdown')->getBannerCollection()):?>
    <?php foreach($countdowns as $cd){ $countdown = $cd;break;}?>
    <?php if( strtotime($countdown->getAltText()) > time()  ):?>
        <div class="header_countdown">
            <div onclick="window.location.href='<?php echo $countdown->getUrl(); ?>'">
                <?php
                    $imag_src = $countdown->getImageUrl();
                    if($imag_src){
                        echo '<img src="'.$imag_src.'"/>';
                    }
                ?>
                <span id="header_countdown" class="PositionAbsolute"></span>
            </div>
            <?php $date_time = strtotime($countdown->getAltText()); ?>
            <script type="text/javascript">
                jQuery(document).ready(function($){
                    countdown('header_countdown', <?php echo date("Y",$date_time)?>, <?php echo date("m",$date_time)?>, <?php echo date("d",$date_time)?>, <?php echo date("H",$date_time)?>, <?php echo date("i",$date_time)?>, <?php echo date("s",$date_time)?>);
                });
            </script>
        </div>
    <?php endif;?>
<?php endif; ?>



