<?php if($this->getCurrencyCount()>1): ?>
<div class="top_currency">
    <label>Currency</label>
    <span><?php echo $this->getCurrentCurrencyCode();?></span>
    <div class="currency_list">
        <?php foreach ($this->getCurrencies() as $_code => $_name): ?>
            <a href="<?php echo $this->getSwitchCurrencyUrl($_code) ?>"><?php echo $_code ?></a>
        <?php endforeach; ?>
    </div>
</div>
<?php endif; ?>
