<script type="text/javascript">

        var us_obj = {
            'US2':{
                'Bust':  {'inch':33.5,'cm':85},
                'Waist': {'inch':33.5,'cm':85},
                'Hips':  {'inch':33.5,'cm':85},
                'Hollow to Floor <br> (Bare Foot)':{'inch':33.5,'cm':85},
                'Height':{'inch':33.5,'cm':85},
            },
            'US4':{
                'Bust':  {'inch':33.5,'cm':85},
                'Waist': {'inch':33.5,'cm':85},
                'Hips':  {'inch':33.5,'cm':85},
                'Hollow to Floor <br> (Bare Foot)':{'inch':33.5,'cm':85},
                'Height':{'inch':33.5,'cm':85},
            },
            'US6':{
                'Bust':  {'inch':33.5,'cm':85},
                'Waist': {'inch':33.5,'cm':85},
                'Hips':  {'inch':33.5,'cm':85},
                'Hollow to Floor <br> (Bare Foot)':{'inch':33.5,'cm':85},
                'Height':{'inch':33.5,'cm':85},
            },
            'US8':{
                'Bust':  {'inch':33.5,'cm':85},
                'Waist': {'inch':33.5,'cm':85},
                'Hips':  {'inch':33.5,'cm':85},
                'Hollow to Floor <br> (Bare Foot)':{'inch':33.5,'cm':85},
                'Height':{'inch':33.5,'cm':85},
            },
            'US10':{
                'Bust':  {'inch':33.5,'cm':85},
                'Waist': {'inch':33.5,'cm':85},
                'Hips':  {'inch':33.5,'cm':85},
                'Hollow to Floor <br> (Bare Foot)':{'inch':33.5,'cm':85},
                'Height':{'inch':33.5,'cm':85},
            },
            'US12':{
                'Bust':  {'inch':33.5,'cm':85},
                'Waist': {'inch':33.5,'cm':85},
                'Hips':  {'inch':33.5,'cm':85},
                'Hollow to Floor <br> (Bare Foot)':{'inch':33.5,'cm':85},
                'Height':{'inch':33.5,'cm':85},
            }

        };

</script>