<script>
    function showMessageDiv(){
        var li_list = '';

        if(jQuery(".new-product-options dl>.no-display").css('display')!='none'){
            jQuery(".new-product-options dl .input-box .required-entry").each(function(){
                if( jQuery(this).css('display') != 'none' ){
                    if(!jQuery(this).val()){
                        li_list += '<li><em>♦</em>'+jQuery(this).parent().data('title')+'</li>';
                    }
                }
            });
        }else{
            jQuery(".new-product-options dl>dd .input-box .required-entry").each(function(){
                if( jQuery(this).css('display') != 'none' ){
                    if(!jQuery(this).val()){
                        li_list += '<li><em>♦</em>'+jQuery(this).parent().data('title')+'</li>';
                    }
                }
            });
        }


        if(li_list){
            var show_content = '';
            show_content += '<div class="va_box">';
            show_content += '<div class="to">⟩</div>';
            show_content += '<div class="va_title">Please Select</div>';
            show_content += '<ul class="va_list">';
            show_content += li_list;
            show_content += '</ul>';
            show_content += '</div>';
            jQuery(".validation-message").html(show_content);
        }
    }
    function hideMessageDivs(){
        jQuery(".validation-message").html('');
    }
</script>
<?php $_product = $this->getProduct(); ?>
<?php $buttonTitle = $this->__('Add to Cart'); ?>

<?php if($_product->isSaleable()): ?>

    <div class="add-to-cart">


        <?php if(!$_product->isGrouped()): ?>
            <div class="quty">
                <label for="qty"><?php echo $this->__('Qty:') ?></label>
                <select name="qty" id="qty" class="qty">
                    <?php for($i=1;$i<61;$i++){?>
                        <option value="<?php echo $i; ?>" <?php if( ($this->getProductDefaultQty() * 1) == $i){echo 'selected';}  ?> ><?php echo $i; ?></option>
                    <?php }?>
                </select>
            </div>
        <?php endif; ?>



        <div class="btns">
            <div class="validation-message"></div>
            <button type="button" title="<?php echo $buttonTitle ?>" id="product-addtocart-button" class="button btn-cart"
                    onmouseout="hideMessageDivs()"
                    onmouseover="showMessageDiv()"
                    onclick="productAddToCartForm.submit(this)"><span><span><?php echo $buttonTitle ?></span></span></button>
            <?php if ($this->helper('wishlist')->isAllow()) : ?>
                <?php $_wishlistSubmitUrl = $this->helper('wishlist')->getAddUrl($_product); ?>
                <a class="wishlist" href="<?php echo $_wishlistSubmitUrl ?>" onclick="productAddToCartForm.submitLight(this, this.href); return false;" class="link-wishlist"><span>♥</span></a>
            <?php endif; ?>
        </div>

    </div>



<?php endif; ?>
