<?php $_description = $this->getProduct()->getDescription(); ?>
<?php if ($_description): ?>
    <h3 class="hua"><?php echo $this->__('Description') ?></h3>
    <div class="std">
        <?php echo $this->helper('catalog/output')->productAttribute($this->getProduct(), $_description, 'description') ?>
    </div>

    <?php if (count($this->getProduct()->getMediaGalleryImages()) > 0): ?>
        <h3 class="hua"><?php echo $this->__("Picture")?></h3>
        <ul>
            <?php foreach ($this->getProduct()->getMediaGalleryImages() as $_image): ?>
                <li>
                    <img src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile()); ?>" alt="<?php echo $this->htmlEscape($_image->getLabel()) ?>" />
                </li>
            <?php endforeach; ?>
        </ul>
    <?php endif; ?>


<?php endif; ?>
