<?php
    $_product = $this->getProduct();
?>

<div class="estorm-zoom" data-config='{"colsnumber":"3", "zindex":"99"}'>
    <div class="estorm-zoom-stage">
        <img width="300"
             height="400"
             data-bigurl="<?php echo $this->helper('catalog/image')->init($_product, 'image')->resize(600,800);?>"
             src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(300,400) ;?>">
    </div>


    <?php if(  $GalleryImages = $this->getGalleryImages()  ):?>

    <?php endif; ?>
    <div class="estorm-zoom-gallery">
        <ul>
            <?php $img_i=0; foreach ($this->getGalleryImages() as $_image): ?>
                <?php if($img_i==0):?>

                    <li class="item current">
                        <a href="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'image',$_image->getFile())->resize(600,800); ?>" data-middle="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'small_image',$_image->getFile())->resize(300,400); ?>">
                            <img src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'small_image',$_image->getFile())->resize(300,400); ?>" width="90" height="120">
                        </a>
                    </li>

                <?php else: ?>

                    <li class="item">
                        <a href="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail',$_image->getFile())->resize(600,800); ?>">
                            <img src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'small_image',$_image->getFile())->resize(300,400); ?>"  width="90" height="120">
                        </a>
                    </li>

                <?php endif;?>
                <?php $img_i++; ?>



            <?php endforeach; ?>
        </ul>
    </div>
</div>

<script>
    jQuery(function($){
        $('.estorm-zoom').estormZoom();
    });
</script>