<?php
    $_product = $this->getProduct();
?>

<div class="estorm-zoom" data-config='{"colsnumber":"3", "zindex":"99"}'>
    <div class="estorm-zoom-stage">
        <img class="m_image"
             data-bigurl="<?php echo $this->helper('catalog/image')->init($_product, 'image')->resize(600,800);?>"
             src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(375,500) ;?>"
             alt="<?php echo $this->escapeHtml($this->getImageLabel());?>" 
             title="<?php echo $this->escapeHtml($this->getImageLabel());?>" />
    </div>


    <?php if(  $GalleryImages = $this->getGalleryImages()  ):?>

    <?php endif; ?>
    <div class="estorm-zoom-gallery">
        <ul>
            <?php $img_i=0; foreach ($this->getGalleryImages() as $_image): ?>
                <?php if($img_i==0):?>

                    <li class="item current">
                        <a href="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'image',$_image->getFile())->resize(600,800); ?>" 
                            data-middle="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'small_image',$_image->getFile())->resize(375,500); ?>"
                            title="<?php echo $this->escapeHtml($_image->getLabel()) ?>">
                            <img src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'small_image',$_image->getFile())->resize(375,500); ?>" 
                                width="90" 
                                height="120"
                                title="<?php echo $this->escapeHtml($_image->getLabel()) ?>"
                                alt="<?php echo $this->escapeHtml($_image->getLabel()) ?>"/>
                        </a>
                    </li>

                <?php else: ?>

                    <li class="item">
                        <a href="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail',$_image->getFile())->resize(600,800); ?>"
                            title="<?php echo $this->escapeHtml($_image->getLabel()) ?>">
                            <img src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'small_image',$_image->getFile())->resize(375,500); ?>"  
                                width="90" 
                                height="120"
                                title="<?php echo $this->escapeHtml($_image->getLabel()) ?>"
                                alt="<?php echo $this->escapeHtml($_image->getLabel()) ?>"/>
                        </a>
                    </li>

                <?php endif;?>
                <?php $img_i++; ?>



            <?php endforeach; ?>
        </ul>
    </div>
</div>

<script>
    jQuery(function($){
        $('.estorm-zoom').estormZoom();
    });
</script>