
<?php $_options = Mage::helper('core')->decorateArray($this->getOptions()) ?>
<?php if (count($_options)):?>
    <script type="text/javascript">
    //<![CDATA[
    var optionFileUpload = {
        productForm : $('product_addtocart_form'),
        formAction : '',
        formElements : {},
        upload : function(element){
            this.formElements = this.productForm.select('input', 'select', 'textarea', 'button');
            this.removeRequire(element.readAttribute('id').sub('option_', ''));

            template = '<iframe id="upload_target" name="upload_target" style="width:0; height:0; border:0;"><\/iframe>';

            Element.insert($('option_'+element.readAttribute('id').sub('option_', '')+'_uploaded_file'), {after: template});

            this.formAction = this.productForm.action;

            var baseUrl = '<?php echo $this->getUrl('*/product/upload') ?>';
            var urlExt = 'option_id/'+element.readAttribute('id').sub('option_', '');

            this.productForm.action = parseSidUrl(baseUrl, urlExt);
            this.productForm.target = 'upload_target';
            this.productForm.submit();
            this.productForm.target = '';
            this.productForm.action = this.formAction;
        },
        removeRequire : function(skipElementId){
            for(var i=0; i<this.formElements.length; i++){
                if (this.formElements[i].readAttribute('id') != 'option_'+skipElementId+'_file' && this.formElements[i].type != 'button') {
                    this.formElements[i].disabled='disabled';
                }
            }
        },
        addRequire : function(skipElementId){
            for(var i=0; i<this.formElements.length; i++){
                if (this.formElements[i].readAttribute('name') != 'options_'+skipElementId+'_file' && this.formElements[i].type != 'button') {
                    this.formElements[i].disabled='';
                }
            }
        },
        uploadCallback : function(data){
            this.addRequire(data.optionId);
            $('upload_target').remove();

            if (data.error) {

            } else {
                $('option_'+data.optionId+'_uploaded_file').value = data.fileName;
                $('option_'+data.optionId+'_file').value = '';
                $('option_'+data.optionId+'_file').hide();
                $('option_'+data.optionId+'').hide();
                template = '<div id="option_'+data.optionId+'_file_box"><a href="#"><img src="var/options/'+data.fileName+'" alt=""><\/a><a href="#" onclick="optionFileUpload.removeFile('+data.optionId+')" title="Remove file" \/>Remove file<\/a>';

                Element.insert($('option_'+data.optionId+'_uploaded_file'), {after: template});
            }
        },
        removeFile : function(optionId)
        {
            $('option_'+optionId+'_uploaded_file').value= '';
            $('option_'+optionId+'_file').show();
            $('option_'+optionId+'').show();

            $('option_'+optionId+'_file_box').remove();
        }
    }
    var optionTextCounter = {
        count : function(field,cntfield,maxlimit){
            if (field.value.length > maxlimit){
                field.value = field.value.substring(0, maxlimit);
            } else {
                cntfield.innerHTML = maxlimit - field.value.length;
            }
        }
    }

    Product.Options = Class.create();
    Product.Options.prototype = {
        initialize : function(config) {
            this.config = config;
            this.reloadPrice();
            document.observe("dom:loaded", this.reloadPrice.bind(this));
        },
        reloadPrice : function() {
            var config = this.config;
            var skipIds = [];
            $$('body .product-custom-option').each(function(element){
                var optionId = 0;
                element.name.sub(/[0-9]+/, function(match){
                    optionId = parseInt(match[0], 10);
                });
                if (config[optionId]) {
                    var configOptions = config[optionId];
                    var curConfig = {price: 0};
                    if (element.type == 'checkbox' || element.type == 'radio') {
                        if (element.checked) {
                            if (typeof configOptions[element.getValue()] != 'undefined') {
                                curConfig = configOptions[element.getValue()];
                            }
                        }
                    } else if(element.hasClassName('datetime-picker') && !skipIds.include(optionId)) {
                        dateSelected = true;
                        $$('.product-custom-option[id^="options_' + optionId + '"]').each(function(dt){
                            if (dt.getValue() == '') {
                                dateSelected = false;
                            }
                        });
                        if (dateSelected) {
                            curConfig = configOptions;
                            skipIds[optionId] = optionId;
                        }
                    } else if(element.type == 'select-one' || element.type == 'select-multiple') {
                        if ('options' in element) {
                            $A(element.options).each(function(selectOption){
                                if ('selected' in selectOption && selectOption.selected) {
                                    if (typeof(configOptions[selectOption.value]) != 'undefined') {
                                        curConfig = configOptions[selectOption.value];
                                    }
                                }
                            });
                        }
                    } else {
                        if (element.getValue().strip() != '') {
                            curConfig = configOptions;
                        }
                    }
                    if(element.type == 'select-multiple' && ('options' in element)) {
                        $A(element.options).each(function(selectOption) {
                            if (('selected' in selectOption) && typeof(configOptions[selectOption.value]) != 'undefined') {
                                if (selectOption.selected) {
                                    curConfig = configOptions[selectOption.value];
                                } else {
                                    curConfig = {price: 0};
                                }
                                optionsPrice.addCustomPrices(optionId + '-' + selectOption.value, curConfig);
                                optionsPrice.reload();
                            }
                        });
                    } else {
                        optionsPrice.addCustomPrices(element.id || optionId, curConfig);
                        optionsPrice.reload();
                    }
                }
            });
        }
    }
    function validateOptionsCallback(elmId, result) {
        var container = $(elmId).up('ul.options-list');
        if (result == 'failed') {
            container.removeClassName('validation-passed');
            container.addClassName('validation-failed');
        } else {
            container.removeClassName('validation-failed');
            container.addClassName('validation-passed');
        }
    }
    var opConfig = new Product.Options(<?php echo $this->getJsonConfig() ?>);
    //]]>
    </script>

    

    
    

    <dl>
        <?php foreach($_options as $_option): ?>
            <?php echo $this->getOptionHtml($_option) ?>
        <?php endforeach; ?>
    </dl>

    <div class="other-description" style="position: absolute;left: 200px;top: 0px;">
        <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('other-descript')->toHtml(); ?>
    </div>



    <div class="<?php if($this->htmlEscape($_option->getTitle()) == 'Enter Color Code') echo 'Color'; else echo 'Size';?> no-display" style="position: absolute;left: 220px;bottom: 20px;">
        <img src="<?php echo $this->getSkinUrl('images/commont/measuring_guide_small.jpg');?>"/>
    </div>




<?php endif; ?>


<script type="text/javascript">
    jQuery("doucument").ready(function(){

        var us_obj = {
            'US2':{
                'Bust':{'inch':33.5,'cm':85},
                'Waist':{'inch':33.5,'cm':85},
                'Hips':{'inch':33.5,'cm':85},
                'Hollow to Floor <br> (Bare Foot)':{'inch':33.5,'cm':85}
            },
            'US4':{
                'Bust':{'inch':33.5,'cm':85},
                'Waist':{'inch':33.5,'cm':85},
                'Hips':{'inch':33.5,'cm':85},
                'Hollow to Floor <br> (Bare Foot)':{'inch':33.5,'cm':85}
            },
            'US6':{
                'Bust':{'inch':33.5,'cm':85},
                'Waist':{'inch':33.5,'cm':85},
                'Hips':{'inch':33.5,'cm':85},
                'Hollow to Floor <br> (Bare Foot)':{'inch':33.5,'cm':85}
            }
        };

        jQuery('#color_A li').hover(function(){
            jQuery('#cbla').empty().append(jQuerjQuery(this).html())   ;                       
        })
        jQuery('#color_B li').hover(function(){
            jQuery('#cblb').empty().append(jQuery(this).html())   ;                       
        })
        jQuery('#color_C li').hover(function(){
            jQuery('#cblc').empty().append(jQuery(this).html())   ;                       
        })
        jQuery('#color_D li').hover(function(){
            jQuery('#cbld').empty().append(jQuery(this).html())   ;                       
        })

        jQuery(".product-custom-option").each(function(){
            var id = jQuery(this).attr("id");

            var maxIndex = jQuery("#"+id+" option:last").prop("index");
            var id_arr = id.split('_');
            var attribute = jQuery("#"+id_arr[1]).val();
            var html = jQuery("."+attribute).html();

            jQuery(this).change(function(){
                var checkText = jQuery(this).find("option:selected").text();
                var checkIndex=jQuery(this).get(0).selectedIndex;
                if(checkIndex == maxIndex)
                {
                    if(jQuery(".insert_US")){
                        jQuery(".insert_US").remove();
                    }
                    jQuery("."+attribute).show();
                }
                else
                {
                    jQuery("."+attribute).hide();

                    if( jQuery(this).parent().data('title') == 'Size'){
                        var us_value ;
                        if( checkText.indexOf("+")>-1 ){
                            us_value = checkText.substring( 0, checkText.indexOf("+") )
                        }else{
                            us_value = checkText;
                        }
                        us_value_key = jQuery.trim(us_value.replace(' ',''));
                        jQuery(this).parent().append(us_template(us_value , us_obj[us_value_key] ));
                    }
                }
            });
        });

        function us_template(us_value,us_obj){
            if(jQuery(".insert_US")){
                jQuery(".insert_US").remove();
            }
            var template = '<div class="insert_US">';
                template += '<p class="infomation">Ddaydress of size <i class="num nomalnum"> '+us_value+' </i> will be made according to the</p>';
                template += '<ul class="compare">';
                jQuery.each(us_obj,function(n,value){
                    template += '<li>';
                    template += '<span class="title">'+n+'</span>';
                    template += '<span class="value">='+value.inch+' inch ('+value.cm+'cm)</span>';
                    template += '</li>';
                });

                template += '</ul>';
                template += '<div class="infomations2">To fit heels,we\'ll add extra 8-13cm onto floor-length dresses.<div class="sizeimage"></div></div>'
                template += '</div>';

            return template;
        }


    });
</script>
