<?php
/**
 * @category    Mana
 * @package     Mana_Filters
 * @copyright   Copyright (c) http://www.manadev.com
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php
/**
 * Category layered navigation state
 *
 * @see Mage_Catalog_Block_Layer_State
 */
/* @var $this Mage_Catalog_Block_Layer_State */
?>
<?php $_filters = $this->getActiveFilters() ?>
<?php if(!empty($_filters)): ?>
<div class="currently">

    <h4>Filter by</h4>
    <ol>
        <?php foreach ($_filters as $_filter): ?>
            <li>
                <span class="value"><?php echo $this->stripTags($_filter->getLabel()) ?></span>
                <a  class="btn-remove" href="<?php echo $_filter->getRemoveUrl() ?>"></a>
            </li>
        <?php endforeach; ?>

    </ol>

</div>
<?php endif; ?>
