<?php if(count($this->getItems())):?>
    <ol>
        <?php foreach ($this->getItems() as $_item):?>
            <li>

                <em class="checkbox"></em>

                <?php if ($_item->getCount() > 0):?>
                    <a href="<?php echo $this->urlEscape($_item->getUrl()) ?>">
                        <?php echo $_item->getLabel() ?>
                    </a>
                <?php else: ?>
                    <?php echo $_item->getLabel() ?>
                <?php endif; ?>

                <?php if ($this->shouldDisplayProductCount()): ?>
                    <span class="filter_count">(<?php echo $_item->getCount() ?>)</span>
                <?php endif; ?>

            </li>
        <?php endforeach ?>
    </ol>
<?php endif;?>