<?php if($this->canShowBlock()): ?>

    <?php echo $this->getStateHtml() ?>


    <div class="filter-nav">

        <?php if($this->canShowOptions()): ?>
            <?php $_filters = $this->getFilters() ?>

                <?php foreach ($_filters as $_filter): ?>
                    <?php if($_filter->getItemsCount()): ?>

                        <dl id="narrow-by-list">
                            <dt><?php echo $this->__($_filter->getName()) ?>:</dt>
                            <dd><?php echo $_filter->getHtml() ?></dd>
                        </dl>
                    <?php endif;?>


                <?php endforeach; ?>

        <?php endif; ?>

    </div>

<?php endif; ?>