<div class="owl-carousel home_banners_1">
    <?php $home_big_banners = Mage::getModel('ibanners/group')->loadByCode('home_big_banners')->getBannerCollection(); ?>
    <?php foreach($home_big_banners as $banner): ?>
        <a class="item" href="<?php echo $banner->getUrl(); ?>">
            <img title="<?php echo $banner->getTitle();?>" alt="<?php echo $banner->getAlt();?>" src="<?php echo $banner->getImageUrl();?>"/>
        </a>
    <?php endforeach; ?>
</div>
<script>
    jQuery(document).ready(function(){
        jQuery('.home_banners_1').each(function() {
            if(jQuery('.item', this).length > 0) {
                jQuery(this).owlCarousel({
                    loop: true,
                    nav: false,
                    items: 1,
                    autoplay: true,
                    autoplayTimeout: 5000,
                    autoplayHoverPause:true
                });
            }
        });
    });
</script>


<div class="home_banners_3">
    <?php $home_banners_3 = Mage::getModel('ibanners/group')->loadByCode('home_banners_3')->getBannerCollection(); ?>
    <?php foreach($home_banners_3 as $banner): ?>
        <a class="item" href="<?php echo $banner->getUrl(); ?>">
            <img title="<?php echo $banner->getTitle();?>" alt="<?php echo $banner->getAlt();?>" src="<?php echo $banner->getImageUrl();?>"/>
        </a>
    <?php endforeach; ?>
    <div class="clearer"></div>
</div>


<div class="MT10 home_category_banners">
    <?php $home_category_banners = Mage::getModel('ibanners/group')->loadByCode('home_category_banners')->getBannerCollection(); ?>
    <?php foreach($home_category_banners as $banner): ?>
        <a class="item" href="<?php echo $banner->getUrl(); ?>">
            <img src="<?php echo $banner->getImageUrl();?>" title="<?php echo $banner->getTitle();?>" alt="<?php echo $banner->getAlt();?>"/>
        </a>
    <?php endforeach; ?>
</div>