<?php
    $Hot_Selling_Products = Mage::getModel('catalog/category')->load(110)
                            ->getProductCollection()
                            ->addAttributeToSelect('*')
                            ->addAttributeToFilter('status', 1)
                            ->addAttributeToFilter('visibility', 4);
?>
<?php if($Hot_Selling_Products->count()>0):?>
    <div class="home_product_title"><h3>Hot Selling Products</h3></div>
    <div class="home_product Hot_Selling_Products owl-carousel">
        <?php foreach($Hot_Selling_Products as $_product):?>

            <dl class="item">
                <dt>
                    <a href="<?php echo $_product->getProductUrl() ?>">
                        <img alt="<?php echo $_product->getName()?>" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(240,320); ?>">
                    </a>
                </dt>
                <dd>
                    <p>
                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_product->getName()?>">
                            <?php echo $_product->getName()?>
                        </a>
                    </p>
                    <div class="home_price">
                        <span><?php echo Mage::app()->getStore()->getCurrentCurrency()->getCode();?></span>
                        <?php echo $this->getPriceHtml($_product, true) ?>
                    </div>
                </dd>
            </dl>

        <?php endforeach; ?>
    </div>

<?php endif;?>




<?php
    $New_Arrival_Products = Mage::getModel('catalog/category')->load(111)
                            ->getProductCollection()
                            ->addAttributeToSelect('*')
                            ->addAttributeToFilter('status', 1)
                            ->addAttributeToFilter('visibility', 4);
?>
<?php if($New_Arrival_Products->count()>0):?>
    <div class="home_product_title"><h3>Low Price Products</h3></div>
    <div class="home_product New_Arrival_Products owl-carousel">
        <?php foreach($New_Arrival_Products as $_product):?>

            <dl class="item">
                <dt>
                    <a href="<?php echo $_product->getProductUrl() ?>">
                        <img alt="<?php echo $_product->getName()?>" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(240,320); ?>">
                    </a>
                </dt>
                <dd>
                    <p>
                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_product->getName()?>">
                            <?php echo $_product->getName()?>
                        </a>
                    </p>
                    <div class="home_price">
                        <span><?php echo Mage::app()->getStore()->getCurrentCurrency()->getCode();?></span>
                        <?php echo $this->getPriceHtml($_product, true) ?>
                    </div>
                </dd>
            </dl>

        <?php endforeach; ?>
    </div>
   
<?php endif;?>

 <script>
        jQuery(document).ready(function(){
            jQuery('.home_product').each(function() {
                if(jQuery('.item', this).length > 0) {
                    jQuery(this).owlCarousel({
                        loop: true,
                        nav: true,
                        dots:false,
                        autoWidth:true,
                        margin:10,
                        autoplay: false
                    });
                }
            });
        });
</script>
