
<div class="MT10 MB10 helpcenter">
    <?php echo $this->getChildHtml('help_left');?>
    <div class="help_right">
        <div class="page-sitemap">

            <div class="page-title" style="border:0">
                <h1>Site Map<?php //echo $this->getTitle() ?></h1>
            </div>

            <div id="sitemap_top_links">
                <?php //echo $this->getChildHtml('links') ?>
            </div>
            <?php echo $this->getChildHtml('pager_top') ?>
            <?php echo $this->getChildHtml('sitemap') ?>
            <?php //echo $this->getChildHtml('links') ?>
            <?php echo $this->getChildHtml('pager_bottom') ?>
        </div>
    </div>
</div>
