<div class="help_right">

    <p><span style="font-size: medium;"><strong>About Us</strong></span></p>

    <p>Islambridal.com is an online factory based manufactuer that make muslimah satisfied with all kinds of dresses we offered, such as wedding dresses and event dresses. Founded by factory manufacturer makes you forget dull and yawn-worthy designs. We bring you unique yet modest design to fulfill your ever-changing taste in the fashion world.</p>

    <p>You want to look fancy, but still be comfortable in the usually hot and humid weather. You want to wear a flattering outfit, but do not want to look a few months pregnant after feasting on all that wedding food. (trust me, the food is almost always amazing)</p>

    <p>Combination of two arabic words meaning 'the castle of the good life' will continuously put up fresh ideas to make a muslimah closet full with fabulous pieces. It is not necessary for you to worry about dresses size, since Islambridal has size S to XXXL and custom measurement.</p>

    <p>You have 6 reasons or even more why you should shop from here. We can also offer wholesale and retail business.</p>
    <p>1. Multi choices of wedding dresses and event dresses</p>
    <p>2. Global standards of all kinds of dresses</p>
    <p>3. Low prices & high quality dresses</p>
    <p>4. Safe & Easy online shopping</p>
    <p>5. Refund Guarantee & kind customer service</p>
    <p>6. Delivery fast around the world</p>

    <p>We accept payment manners of Western Union, credit Cards, wire transfer and paypal. We have been improved by McAfee and VeriSign,  so you will be secured that your transaction is safe.</p>
    <p>Because we aim for good feedback from our clients, we also put effort when it comes to the dresses delivery, so we have top company partners, like UPS and DHL, in transporting the items correctly and swiftly right in the front of your door. We always deliver with great service wherever you are located and whoever you are, if you need a support from us, islambridal’s customer service will be providing you the best service you could ever ask for.</p>


</div>