<div class="help_right"><p><span style="font-size: medium;"><strong>How To Order</strong></span></p>

    <p>Follow the steps below to complete your order.</p>
    <p>Step 1: Login / Register</p>
    <p><img src="<?php echo $this->getUrl()?>/skin/frontend/pc/default/images/helpcenter/a.png"/></p>
    <p>If you have not created your account, click on “Sign Up” button. Enter you information required and click on “Register” button. If you have register with us, click on the "Login As Member" button to login.</p>

    <p>Step 2 : Find your dresses and Add it to Cart (Choose your desire item, insert the quantity of the item and click on “Add to cart” button. )</p>
    <p><img src="<?php echo $this->getUrl()?>/skin/frontend/pc/default/images/helpcenter/b.png"/></p>

    <p>Step 3: Checkout Out</p>
    <p><img src="<?php echo $this->getUrl()?>/skin/frontend/pc/default/images/helpcenter/c.png"/></p>
    <p>Click on "Continue Shopping" to add more items into your cart. When you finish shopping click on “Secure Checkout” to proceed with your purchase.</p>

    <p>Step 4: Enter Shipping Address (For New Customer)</p>
    <p><img src="<?php echo $this->getUrl()?>/skin/frontend/pc/default/images/helpcenter/d.png"/></p>
    <p>For new customer, click on the "Add Address" button to add your shipping address first before proceed to payment.</p>


    <p>Step 5: Confirm Your Delivery Details</p>


</div>