<div class="help_right"><p><span style="font-size: medium;"><strong>Login Problems</strong></span></p>

    <p>Sign up Steps:</p>
    <p>Click “Join Free” on website right place.</p>
    <p>Input Email, Password, and click Register button. Then, you will receive a sign up confirmation message.</p>
    <p>Login Problems:</p>
    <p>If you have troubles to log in, Please follow the instructions below:</p>
    <p>You can check whether your user-name is correct which you used for registration or not.</p>
    <p>You need ensure that cookies from our website is accepted in your browser (Internet Explorer or others).</p>
    <p>If the above methods still do not work, please contact our customer service, they will help you to resolve the problem.</p>
    <p>TIPs: If you're not sure whether the problem is ours or yours, please test logging in with a different set of computer, or try different browsers.</p>
    <p>When you registered, you made a mistake which caused that you can't access your account, and you've never made any orders. You’d better to registrant for a new account.</p>

</div>