<?php /**  CMS Layout Update XML **********
<reference name="content">
<remove name="cms.wrapper"/>
<block type="core/template" name="main" template="helpcenter/main.phtml" >
<block type="core/template" name="help_left" template="helpcenter/left.phtml" />
<block type="core/template" name="help_right" template="helpcenter/size_chart.phtml" />
</block>
</reference>
 * **/?>


<div class="MT10 MB10">
    <?php echo $this->getChildHtml('',true,true);?>
</div>
