<?php /**  CMS Layout Update XML **********
<reference name="content">
<block type="core/template" name="main" template="helpcenter/main.phtml" >
<block type="core/template" name="help_left" template="helpcenter/left.phtml" />
<block type="core/template" name="help_right" template="helpcenter/help.phtml" />
</block>
</reference>
 * **/?>
<style>
    .std{display:none;}
</style>

<div class="MT10 MB10 helpcenter">
    <div class="help_left">
        <?php echo $this->getChildHtml('help_left');?>
        <script>
            var pathname =  window.location.pathname;
            jQuery("a[href*='"+pathname+"']").css("color","#f39");
        </script>
    </div>

    <?php echo $this->getChildHtml('help_right');?>
</div>
