<div class="help_right">
    <p><span style="font-size: medium;"><strong>Return and Exchange Policy</strong></span></p>
    <p>Return and exchange policy:</p>
    <p>Returning For Replacement or Refund</p>
    <p>We uphold the principle of "quality first, customer foremost". Your satisfaction is our destination! When the package arrived, we sincerely encourage you to try it/them on as soon as possible without removing the tags, altering, or washing. All the dresses are not in stock, whether choosing a standard size or custom size. All the dresses are personally tailored for you from scratch. Once your order is confirmed, our tailors begin selecting materials in the color you requested and cutting fabric based on your measurements. Even standard size dresses are made to measure for each customer. The custom nature of our dresses means our cancellation policy and return policy is stricter than other companies. So it's important to order carefully, you can contact our online sale for professional help of choosing the right style, size or color before you order.</p>
    <p>Attention: We do not accept returning for personal reasons, such as "I do not like it on me” or "I only want one of the dresses received”.</p>

    <p>Defective, Damaged or Misshipped Items</p>
    <p>Please kindly check the package contents before signing. You can get a refund of the full purchase price plus shipping costs for defective, damaged or mis-shipped items. If your items were damaged during delivery, we suggest you to take photos or video and get a "Proof of Damage" documentation from the delivery carrier. Quality problem can be defined as obvious quality defects, then no following of customization requirement and size deviation from the posted size criteria.</p>

    <p>Sizing or Fitting Issues</p>
    <p>Before ordering a dress, please kindly make sure to give us the exact size measurement. The finished gown may vary by approximately one inch in either direction of the specified measurements. For the dispute on size deviation, please take some photographs of the merchandise by laying it on the ground and place a tape ruler to measure out the problem. You shall submit the photographs to islambridal@aol.com and we'll have the designated personnel to take the dispute and offer a reply within 24 hours.</p>

    <p>Dress is not the size you ordered</p>
    <p>If the dress's size differs from the specifications you ordered by more than one inch, we cordially encourage you to find a local tailor to make adjustments. All of our dresses (except ready-to-ship dresses) are newly tailored by our dressmakers. There may be the little size error within one inch for the handwork. Please kindly forgive.</p>

    <p>Dress is the custom size you ordered but does not fit</p>
    <p>Considering the uniqueness of the product in the event of Custom Made, dresses following the specifications you ordered cannot be returned or exchanged. But we attach an fabric in the seams of your dress, you can make minor adjustments at a local tailor of which we won't cover the cost. Please note: if your order specifications differ too much from the final sizing request, re-sizing may not be possible.</p>
    <p>If you're sure that you get a dress which is not tailored by the specification of your order, please take some photos of the merchandise by laying it on the ground and place a tape ruler to measure out the problem. You shall submit the photographs to
        islambridal@aol.com and we'll have the designated personnel to take the dispute and offer a reply within 24 hours. We will help you to settle the problem quickly.</p>

    <p>Color Mismatch</p>
    <p>There is a little color difference of the same color for the different fabrics. Some kinds of fabrics will show different color effect when you check it from different angles under different light, such as taffeta. Different monitors will also show the different color effect from the actual color of the dresses. The slight color difference between the dress at hand and the color shown on the monitor is not the color defective or wrong delivery. However, if you confirm that you receive a dress in wrong color; please kindly send e-mail to islambridal@aol.com. We will help you.</p>

    <p>Return Process</p>
    <p>We do NOT accept any return or exchange without rational reasons. Returns must be arranged within 5 days. We will offer refund only of products which are defected, or sent by mistake. We couldn't accept returns on following condition:</p>
    <p>a. Special Orders - dresses and other items made or ordered specifically for you according to the style (custom design), custom color (not picture color) and personal size (custom size) you required.</p>
    <p>b. Specialty Items – dresses and other items on Sale or Price Reduced & Non-stock.</p>
    <p>c. Wrong Size & Wrong Color & Wrong Style & Unsatisfied Style ordered by yourself - We have no control and accept no responsibility for the size/ color /style you select for your merchandise.</p>
    <p>Step One: Get a Return Authorization number</p>
    <p>Finish and send a return request to customer service mailbox within 5 days after you received the package. It should include an explanation and photographs documenting the reason for the return. Returns will not be accepted without prior approval from Customer Service. Once Customer Service approves your request, Return Authorization Number will be attached in the confirmation email; Packages without Return Authorization Number will be REFUSED and will not be refunded or exchanged.</p>
    <p>Step Two: Inspect merchandise</p>
    <p>All returned or exchanged items must:</p>
    <p>be unworn / unaltered / unwashed/ odorless</p>
    <p>have no stains, rips, odors or damage of any kind</p>
    <p>be returned with all accessories including shawl and straps</p>
    <p>Step Three: Ship merchandise to our Warehouse</p>
    <p>Please be sure that the item(s) can be sent out within 5 days after you get the Return Authorization Number, or we reserve the right to refuse the return. Put your Return Authorization Number clearly on the outside of the package. Please send item(s) and offer us the tracking number and tracking website within 5 days from the time you get the Return Authorization Number from us, or we will Not accept return and refund after 5 days.</p>

    <p>Islambridal only accepts prepaid packages. We do not accept C.O.D. If it's a mistake made by us, then you will be reimbursed for the return shipping.</p>
    <p>If the dresses are not in their original condition, we may charge higher processing fee to cover our lose. Your order may not be refundable if the dresses turn out to be impossible to be resold!</p>
    <p>Please use post mail instead of express delivery to return the items to save your shipping cost and avoid tax in our side.</p>
    <p>Step Four: Credit or Exchange</p>
    <p>Once we received your item, your return will be processed in 3 to 5 business days. After our confirmation of your return, please allow up to two billing cycles(Less than 30 days) for it to be credited to your account. Items returned in unacceptable condition will not be processed as refunds and cannot be shipped back to you.</p>


</div>