<div class="help_right">
	<style type="text/css">
        .wedtable { border-left: 1px solid #ccc; border-top: 1px solid #ccc;}
        .wedtable th{ height:31px; line-height:31px;color: #fff;
            text-align: center;
            font-weight: bold;}
        .wedtable td{font-size: 12px;text-align: center;font-family: Arial;height: 20px;line-height: 20px;border-right: 1px solid #ccc;border-bottom: 1px solid #ccc;}
	</style>
	<dl class="SizeChart">
		<dd>
		<dl class="sizechard">
			<dt><strong>Regular Sizing</strong></dt>
			<dd>
			<table class="wedtable" border="0" width="100%">
			<tbody>
			<tr>
				<th style="background: #f39;" colspan="17">
					Dress Size Chart
				</th>
			</tr>
			<tr>
				<td class="wedtdbg">
					US Size
				</td>
				<td colspan="2">
					2
				</td>
				<td colspan="2">
					4
				</td>
				<td colspan="2">
					6
				</td>
				<td colspan="2">
					8
				</td>
				<td colspan="2">
					10
				</td>
				<td colspan="2">
					12
				</td>
				<td colspan="2">
					14
				</td>
				<td colspan="2">
					16
				</td>
			</tr>
			<tr>
				<td class="wedtdbg">
					Europe Size
				</td>
				<td colspan="2">
					32
				</td>
				<td colspan="2">
					34
				</td>
				<td colspan="2">
					36
				</td>
				<td colspan="2">
					38
				</td>
				<td colspan="2">
					40
				</td>
				<td colspan="2">
					42
				</td>
				<td colspan="2">
					44
				</td>
				<td colspan="2">
					46
				</td>
			</tr>
			<tr>
				<td class="wedtdbg">
					UK Size
				</td>
				<td colspan="2">
					6
				</td>
				<td colspan="2">
					8
				</td>
				<td colspan="2">
					10
				</td>
				<td colspan="2">
					12
				</td>
				<td colspan="2">
					14
				</td>
				<td colspan="2">
					16
				</td>
				<td colspan="2">
					18
				</td>
				<td colspan="2">
					20
				</td>
			</tr>
			<tr>
				<td class="wedtdbg">
					&nbsp;
				</td>
				<td>
					inch
				</td>
				<td>
					cm
				</td>
				<td>
					inch
				</td>
				<td>
					cm
				</td>
				<td>
					inch
				</td>
				<td>
					cm
				</td>
				<td>
					inch
				</td>
				<td>
					cm
				</td>
				<td>
					inch
				</td>
				<td>
					cm
				</td>
				<td>
					inch
				</td>
				<td>
					cm
				</td>
				<td>
					inch
				</td>
				<td>
					cm
				</td>
				<td>
					inch
				</td>
				<td>
					cm
				</td>
			</tr>
			<tr>
				<td class="wedtdbg">
					Bust
				</td>
				<td>
					32.5
				</td>
				<td>
					83
				</td>
				<td>
					33.5
				</td>
				<td>
					85
				</td>
				<td>
					34.5
				</td>
				<td>
					88
				</td>
				<td>
					35.5
				</td>
				<td>
					90
				</td>
				<td>
					36.5
				</td>
				<td>
					93
				</td>
				<td>
					38
				</td>
				<td>
					97
				</td>
				<td>
					39.5
				</td>
				<td>
					100
				</td>
				<td>
					41
				</td>
				<td>
					104
				</td>
			</tr>
			<tr>
				<td class="wedtdbg">
					Waist
				</td>
				<td>
					25.5
				</td>
				<td>
					65
				</td>
				<td>
					26.5
				</td>
				<td>
					68
				</td>
				<td>
					27.5
				</td>
				<td>
					70
				</td>
				<td>
					28.5
				</td>
				<td>
					72
				</td>
				<td>
					29.5
				</td>
				<td>
					75
				</td>
				<td>
					31
				</td>
				<td>
					79
				</td>
				<td>
					32.5
				</td>
				<td>
					83
				</td>
				<td>
					34
				</td>
				<td>
					86
				</td>
			</tr>
			<tr>
				<td class="wedtdbg">
					Hips
				</td>
				<td>
					35.75
				</td>
				<td>
					91
				</td>
				<td>
					36.75
				</td>
				<td>
					92
				</td>
				<td>
					37.75
				</td>
				<td>
					96
				</td>
				<td>
					38.75
				</td>
				<td>
					98
				</td>
				<td>
					39.75
				</td>
				<td>
					101
				</td>
				<td>
					41.25
				</td>
				<td>
					105
				</td>
				<td>
					42.75
				</td>
				<td>
					109
				</td>
				<td>
					44.25
				</td>
				<td>
					112
				</td>
			</tr>
			<tr>
				<td class="wedtdbg">
					Hollow to Floor
				</td>
				<td>
					58
				</td>
				<td>
					147
				</td>
				<td>
					58
				</td>
				<td>
					147
				</td>
				<td>
					59
				</td>
				<td>
					150
				</td>
				<td>
					59
				</td>
				<td>
					150
				</td>
				<td>
					60
				</td>
				<td>
					152
				</td>
				<td>
					60
				</td>
				<td>
					152
				</td>
				<td>
					61
				</td>
				<td>
					155
				</td>
				<td>
					61
				</td>
				<td>
					155
				</td>
			</tr>
			<tr>
				<td class="wedtdbg">
					Shoulder
				</td>
				<td>
					14 4/7
				</td>
				<td>
					37
				</td>
				<td>
					15
				</td>
				<td>
					38
				</td>
				<td>
					15
				</td>
				<td>
					38
				</td>
				<td>
					15 1/3
				</td>
				<td>
					39
				</td>
				<td>
					15 3/4
				</td>
				<td>
					40
				</td>
				<td>
					16 1/7
				</td>
				<td>
					41
				</td>
				<td>
					16 1/2
				</td>
				<td>
					42
				</td>
				<td>
					17
				</td>
				<td>
					43
				</td>
			</tr>
			<tr>
				<td class="wedtdbg">
					Arm Length
				</td>
				<td>
					18
				</td>
				<td>
					45 1/2
				</td>
				<td>
					18
				</td>
				<td>
					45 1/2
				</td>
				<td>
					18
				</td>
				<td>
					45 1/2
				</td>
				<td>
					18
				</td>
				<td>
					45 1/2
				</td>
				<td>
					18
				</td>
				<td>
					45 1/2
				</td>
				<td>
					18
				</td>
				<td>
					45 1/2
				</td>
				<td>
					18
				</td>
				<td>
					45 1/2
				</td>
				<td>
					18
				</td>
				<td>
					45 1/2
				</td>
			</tr>
			<tr>
				<td class="wedtdbg">
					Armscye
				</td>
				<td>
					15
				</td>
				<td>
					38
				</td>
				<td>
					15 1/3
				</td>
				<td>
					39
				</td>
				<td>
					16
				</td>
				<td>
					40 1/2
				</td>
				<td>
					16 1/3
				</td>
				<td>
					41 1/2
				</td>
				<td>
					16 3/4
				</td>
				<td>
					42 1/2
				</td>
				<td>
					17 1/3
				</td>
				<td>
					44
				</td>
				<td>
					18
				</td>
				<td>
					45 1/2
				</td>
				<td>
					18 1/2
				</td>
				<td>
					47
				</td>
			</tr>
			</tbody>
			</table>
			</dd>
		</dl>
		<dl class="sizechard" style="margin-top: 20px;">
			<dt><strong>Plus Sizing</strong></dt>
			<dd>
			<table class="wedtable" border="0" width="100%">
			<tbody>
			<tr>
				<th style="background: #f39;" colspan="15">
					Plus Size Dress Size Chart
				</th>
			</tr>
			<tr>
				<td class="wedtdbg">
					Plus Size (US)
				</td>
				<td colspan="2">
					14W
				</td>
				<td colspan="2">
					16W
				</td>
				<td colspan="2">
					18W
				</td>
				<td colspan="2">
					20W
				</td>
				<td colspan="2">
					22W
				</td>
				<td colspan="2">
					24W
				</td>
				<td colspan="2">
					26W
				</td>
			</tr>
			<tr>
				<td class="wedtdbg">
					Europe Size
				</td>
				<td colspan="2">
					44
				</td>
				<td colspan="2">
					46
				</td>
				<td colspan="2">
					48
				</td>
				<td colspan="2">
					50
				</td>
				<td colspan="2">
					52
				</td>
				<td colspan="2">
					54
				</td>
				<td colspan="2">
					56
				</td>
			</tr>
			<tr>
				<td class="wedtdbg">
					UK Size
				</td>
				<td colspan="2">
					18
				</td>
				<td colspan="2">
					20
				</td>
				<td colspan="2">
					22
				</td>
				<td colspan="2">
					24
				</td>
				<td colspan="2">
					26
				</td>
				<td colspan="2">
					28
				</td>
				<td colspan="2">
					30
				</td>
			</tr>
			<tr>
				<td class="wedtdbg">
					&nbsp;
				</td>
				<td>
					inch
				</td>
				<td>
					cm
				</td>
				<td>
					inch
				</td>
				<td>
					cm
				</td>
				<td>
					inch
				</td>
				<td>
					cm
				</td>
				<td>
					inch
				</td>
				<td>
					cm
				</td>
				<td>
					inch
				</td>
				<td>
					cm
				</td>
				<td>
					inch
				</td>
				<td>
					cm
				</td>
				<td>
					inch
				</td>
				<td>
					cm
				</td>
			</tr>
			<tr>
				<td class="wedtdbg">
					Bust
				</td>
				<td>
					41
				</td>
				<td>
					104
				</td>
				<td>
					43
				</td>
				<td>
					109
				</td>
				<td>
					45
				</td>
				<td>
					114
				</td>
				<td>
					47
				</td>
				<td>
					119
				</td>
				<td>
					49
				</td>
				<td>
					124
				</td>
				<td>
					51
				</td>
				<td>
					130
				</td>
				<td>
					53
				</td>
				<td>
					135
				</td>
			</tr>
			<tr>
				<td class="wedtdbg">
					Waist
				</td>
				<td>
					34
				</td>
				<td>
					86
				</td>
				<td>
					36.25
				</td>
				<td>
					92
				</td>
				<td>
					38.5
				</td>
				<td>
					98
				</td>
				<td>
					40.75
				</td>
				<td>
					104
				</td>
				<td>
					43
				</td>
				<td>
					109
				</td>
				<td>
					45.25
				</td>
				<td>
					115
				</td>
				<td>
					47.5
				</td>
				<td>
					121
				</td>
			</tr>
			<tr>
				<td class="wedtdbg">
					Hips
				</td>
				<td>
					43.5
				</td>
				<td>
					110
				</td>
				<td>
					45.5
				</td>
				<td>
					116
				</td>
				<td>
					47.5
				</td>
				<td>
					121
				</td>
				<td>
					49.5
				</td>
				<td>
					126
				</td>
				<td>
					51.5
				</td>
				<td>
					131
				</td>
				<td>
					53.5
				</td>
				<td>
					136
				</td>
				<td>
					55.5
				</td>
				<td>
					141
				</td>
			</tr>
			<tr>
				<td class="wedtdbg">
					Hollow to Floor
				</td>
				<td>
					61
				</td>
				<td>
					155
				</td>
				<td>
					61
				</td>
				<td>
					155
				</td>
				<td>
					61
				</td>
				<td>
					155
				</td>
				<td>
					61
				</td>
				<td>
					155
				</td>
				<td>
					61
				</td>
				<td>
					155
				</td>
				<td>
					61
				</td>
				<td>
					155
				</td>
				<td>
					61
				</td>
				<td>
					155
				</td>
			</tr>
			<tr>
				<td class="wedtdbg">
					Shoulder
				</td>
				<td>
					17 1/3
				</td>
				<td>
					44
				</td>
				<td>
					17 5/7
				</td>
				<td>
					45
				</td>
				<td>
					18 1/9
				</td>
				<td>
					46
				</td>
				<td>
					18 1/2
				</td>
				<td>
					47
				</td>
				<td>
					18 8/9
				</td>
				<td>
					48
				</td>
				<td>
					18 8/9
				</td>
				<td>
					48
				</td>
				<td>
					19 2/7
				</td>
				<td>
					49
				</td>
			</tr>
			<tr>
				<td class="wedtdbg">
					Arm Length
				</td>
				<td>
					18
				</td>
				<td>
					45 1/2
				</td>
				<td>
					18
				</td>
				<td>
					45 1/2
				</td>
				<td>
					18 1/2
				</td>
				<td>
					47
				</td>
				<td>
					19
				</td>
				<td>
					48 1/2
				</td>
				<td>
					19
				</td>
				<td>
					48 1/2
				</td>
				<td>
					19 1/2
				</td>
				<td>
					49
				</td>
				<td>
					19 1/2
				</td>
				<td>
					49 1/2
				</td>
			</tr>
			<tr>
				<td class="wedtdbg">
					Armscye
				</td>
				<td>
					18 5/7
				</td>
				<td>
					47 1/2
				</td>
				<td>
					19 2/7
				</td>
				<td>
					49
				</td>
				<td>
					20 1/2
				</td>
				<td>
					52
				</td>
				<td>
					20 2/3
				</td>
				<td>
					52 1/2
				</td>
				<td>
					20 4/5
				</td>
				<td>
					52 4/5
				</td>
				<td>
					21 2/5
				</td>
				<td>
					54 1/2
				</td>
				<td>
					21 1/2
				</td>
				<td>
					54 3/5
				</td>
			</tr>
			</tbody>
			</table>
			</dd>
		</dl>
		</dd>
	</dl>
	<style type="text/css">
.Chart table{  border-left: 1px solid #ccc;border-top: 1px solid #ccc;width:100%;}
.Chart table th{background: #f39;border-right: 1px solid #ccc;border-bottom: 1px solid #ccc;height: 30px;line-height: 30px;font-size: 11px;color: #fff;font-weight: normal;text-align: center;font-weight: bold;}
.wedtable .wedtdbg{  background: none repeat scroll 0 0 #f7f7f7;color: #666;}
.Chart table td{  border-right: 1px solid #d1d1d1;border-bottom: 1px solid #d1d1d1;height: 20px;line-height: 20px;color: #666;padding: 0 5px;font-size: 11px;text-align: center;}
	</style>
	<div id="zzjs_nav3" class="Chart" style="padding-top: 0px; border-top-style: none;">
		<table class="wedtable" style="margin-top: 30px;" border="0">
		<tbody>
		<tr>
			<th colspan="17">
				&nbsp;Mini Jacket/Wrap Size Chart
			</th>
		</tr>
		<tr>
			<td class="wedtdbg">
				US Size
			</td>
			<td colspan="2">
				2
			</td>
			<td colspan="2">
				4
			</td>
			<td colspan="2">
				6
			</td>
			<td colspan="2">
				8
			</td>
			<td colspan="2">
				10
			</td>
			<td colspan="2">
				12
			</td>
			<td colspan="2">
				14
			</td>
			<td colspan="2">
				16
			</td>
		</tr>
		<tr>
			<td class="wedtdbg">
				European Size
			</td>
			<td colspan="2">
				32
			</td>
			<td colspan="2">
				34
			</td>
			<td colspan="2">
				36
			</td>
			<td colspan="2">
				38
			</td>
			<td colspan="2">
				40
			</td>
			<td colspan="2">
				42
			</td>
			<td colspan="2">
				44
			</td>
			<td colspan="2">
				46
			</td>
		</tr>
		<tr>
			<td class="wedtdbg">
				UK Size
			</td>
			<td colspan="2">
				6
			</td>
			<td colspan="2">
				8
			</td>
			<td colspan="2">
				10
			</td>
			<td colspan="2">
				12
			</td>
			<td colspan="2">
				14
			</td>
			<td colspan="2">
				16
			</td>
			<td colspan="2">
				18
			</td>
			<td colspan="2">
				20
			</td>
		</tr>
		<tr>
			<td class="wedtdbg">
				&nbsp;
			</td>
			<td>
				inch
			</td>
			<td>
				cm
			</td>
			<td>
				inch
			</td>
			<td>
				cm
			</td>
			<td>
				inch
			</td>
			<td>
				cm
			</td>
			<td>
				inch
			</td>
			<td>
				cm
			</td>
			<td>
				inch
			</td>
			<td>
				cm
			</td>
			<td>
				inch
			</td>
			<td>
				cm
			</td>
			<td>
				inch
			</td>
			<td>
				cm
			</td>
			<td>
				inch
			</td>
			<td>
				cm
			</td>
		</tr>
		<tr>
			<td class="wedtdbg">
				Bust
			</td>
			<td>
				32 2/3
			</td>
			<td>
				83
			</td>
			<td>
				33
			</td>
			<td>
				84
			</td>
			<td>
				34 2/3
			</td>
			<td>
				88
			</td>
			<td>
				35 3/7
			</td>
			<td>
				90
			</td>
			<td>
				36 3/5
			</td>
			<td>
				93
			</td>
			<td>
				38 1/5
			</td>
			<td>
				97
			</td>
			<td>
				39 3/8
			</td>
			<td>
				100
			</td>
			<td>
				41
			</td>
			<td>
				104
			</td>
		</tr>
		<tr>
			<td class="wedtdbg">
				Shoulder
			</td>
			<td>
				14 4/7
			</td>
			<td>
				37
			</td>
			<td>
				15
			</td>
			<td>
				38
			</td>
			<td>
				15
			</td>
			<td>
				38
			</td>
			<td>
				15 1/3
			</td>
			<td>
				39
			</td>
			<td>
				15 3/4
			</td>
			<td>
				40
			</td>
			<td>
				16 1/7
			</td>
			<td>
				41
			</td>
			<td>
				16 1/2
			</td>
			<td>
				42
			</td>
			<td>
				17
			</td>
			<td>
				43
			</td>
		</tr>
		<tr>
			<td class="wedtdbg">
				Arm Length
			</td>
			<td>
				18
			</td>
			<td>
				45 1/2
			</td>
			<td>
				18
			</td>
			<td>
				45 1/2
			</td>
			<td>
				18
			</td>
			<td>
				45 1/2
			</td>
			<td>
				18
			</td>
			<td>
				45 1/2
			</td>
			<td>
				18
			</td>
			<td>
				45 1/2
			</td>
			<td>
				18
			</td>
			<td>
				45 1/2
			</td>
			<td>
				18
			</td>
			<td>
				45 1/2
			</td>
			<td>
				18
			</td>
			<td>
				45 1/2
			</td>
		</tr>
		<tr>
			<td class="wedtdbg">
				Armscye
			</td>
			<td>
				15
			</td>
			<td>
				38
			</td>
			<td>
				15 1/3
			</td>
			<td>
				39
			</td>
			<td>
				16
			</td>
			<td>
				40 1/2
			</td>
			<td>
				16 1/3
			</td>
			<td>
				41 1/2
			</td>
			<td>
				16 3/4
			</td>
			<td>
				42 1/2
			</td>
			<td>
				17 1/3
			</td>
			<td>
				44
			</td>
			<td>
				18
			</td>
			<td>
				45 1/2
			</td>
			<td>
				18 1/2
			</td>
			<td>
				47
			</td>
		</tr>
		</tbody>
		</table>
		<table class="wedtable" style="margin-top: 30px;" border="0" width="100%">
		<tbody>
		<tr>
			<th colspan="15">
				&nbsp;Plus Size Mini Jacket/Wrap Size Chart
			</th>
		</tr>
		<tr>
			<td class="wedtdbg">
				Plus Size (US)
			</td>
			<td colspan="2">
				14W
			</td>
			<td colspan="2">
				16W
			</td>
			<td colspan="2">
				18W
			</td>
			<td colspan="2">
				20W
			</td>
			<td colspan="2">
				22W
			</td>
			<td colspan="2">
				24W
			</td>
			<td colspan="2">
				26W
			</td>
		</tr>
		<tr>
			<td class="wedtdbg">
				Europe Size
			</td>
			<td colspan="2">
				44
			</td>
			<td colspan="2">
				46
			</td>
			<td colspan="2">
				48
			</td>
			<td colspan="2">
				50
			</td>
			<td colspan="2">
				52
			</td>
			<td colspan="2">
				54
			</td>
			<td colspan="2">
				56
			</td>
		</tr>
		<tr>
			<td class="wedtdbg">
				UK Size
			</td>
			<td colspan="2">
				18
			</td>
			<td colspan="2">
				20
			</td>
			<td colspan="2">
				22
			</td>
			<td colspan="2">
				24
			</td>
			<td colspan="2">
				26
			</td>
			<td colspan="2">
				28
			</td>
			<td colspan="2">
				30
			</td>
		</tr>
		<tr>
			<td class="wedtdbg">
				&nbsp;
			</td>
			<td>
				inch
			</td>
			<td>
				cm
			</td>
			<td>
				inch
			</td>
			<td>
				cm
			</td>
			<td>
				inch
			</td>
			<td>
				cm
			</td>
			<td>
				inch
			</td>
			<td>
				cm
			</td>
			<td>
				inch
			</td>
			<td>
				cm
			</td>
			<td>
				inch
			</td>
			<td>
				cm
			</td>
			<td>
				inch
			</td>
			<td>
				cm
			</td>
		</tr>
		<tr>
			<td class="wedtdbg">
				Bust
			</td>
			<td>
				42 1/2
			</td>
			<td>
				108
			</td>
			<td>
				44
			</td>
			<td>
				112
			</td>
			<td>
				45 2/3
			</td>
			<td>
				116
			</td>
			<td>
				46 6/7
			</td>
			<td>
				119
			</td>
			<td>
				48 3/7
			</td>
			<td>
				124
			</td>
			<td>
				51 1/6
			</td>
			<td>
				130
			</td>
			<td>
				53 1/7
			</td>
			<td>
				135
			</td>
		</tr>
		<tr>
			<td class="wedtdbg">
				Shoulder
			</td>
			<td>
				17 1/3
			</td>
			<td>
				44
			</td>
			<td>
				17 5/7
			</td>
			<td>
				45
			</td>
			<td>
				18 1/9
			</td>
			<td>
				46
			</td>
			<td>
				18 1/2
			</td>
			<td>
				47
			</td>
			<td>
				18 8/9
			</td>
			<td>
				48
			</td>
			<td>
				18 8/9
			</td>
			<td>
				48
			</td>
			<td>
				19 2/7
			</td>
			<td>
				49
			</td>
		</tr>
		<tr>
			<td class="wedtdbg">
				Arm Length
			</td>
			<td>
				18
			</td>
			<td>
				45 1/2
			</td>
			<td>
				18
			</td>
			<td>
				45 1/2
			</td>
			<td>
				18 1/2
			</td>
			<td>
				47
			</td>
			<td>
				19
			</td>
			<td>
				48 1/2
			</td>
			<td>
				19
			</td>
			<td>
				48 1/2
			</td>
			<td>
				19 1/2
			</td>
			<td>
				49
			</td>
			<td>
				19 1/2
			</td>
			<td>
				49 1/2
			</td>
		</tr>
		<tr>
			<td class="wedtdbg">
				Armscye
			</td>
			<td>
				18 5/7
			</td>
			<td>
				47 1/2
			</td>
			<td>
				19 2/7
			</td>
			<td>
				49
			</td>
			<td>
				20 1/2
			</td>
			<td>
				52
			</td>
			<td>
				20 2/3
			</td>
			<td>
				52 1/2
			</td>
			<td>
				20 4/5
			</td>
			<td>
				52 4/5
			</td>
			<td>
				20 5/8
			</td>
			<td>
				52 2/5
			</td>
			<td>
				21 1/2
			</td>
			<td>
				54 3/5
			</td>
		</tr>
		</tbody>
		</table>
		<p class="wedp">
			The sleeve length varies due to different styles of the jacket, so we will make the sleeve according to the jacket image and the exact size of your item. If you have any other special requests, please feel free to contact us.
		</p>
	</div>
	<style type="text/css">
.Chart table{  border-left: 1px solid #ccc;border-top: 1px solid #ccc;width: 100%;}
.Chart table th{background: #f39;border-right: 1px solid #ccc;border-bottom: 1px solid #ccc;height: 30px;line-height: 30px;font-size: 11px;color: #fff;font-weight: normal;text-align: center;font-weight: bold;}
.wedtable .wedtdbg{  background: none repeat scroll 0 0 #f7f7f7;color: #666;}
.Chart table td{  border-right: 1px solid #d1d1d1;border-bottom: 1px solid #d1d1d1;height: 20px;line-height: 20px;color: #666;padding: 0 5px;font-size: 11px;text-align: center;}
	</style>
	<div class="Chart" id="zzjs_nav3" style="padding-top: 0px; border-top-style: none;">
		&nbsp;
	</div>
	<table class="chart-style" width="100%">
	<tbody>
	<tr>
		<td style="background: #f39; color: #fff;" colspan="15">
			<strong><span style="font-size: small; font-weight: normal;">Junior Bridesmaid Dresses Size Chart</span></strong>
		</td>
	</tr>
	<tr>
		<td class="first">
			Size
		</td>
		<td colspan="2">
			J4
		</td>
		<td colspan="2">
			J6
		</td>
		<td colspan="2">
			J8
		</td>
		<td colspan="2">
			J10
		</td>
		<td colspan="2">
			J12
		</td>
		<td colspan="2">
			J14
		</td>
		<td colspan="2">
			J16
		</td>
	</tr>
	<tr>
		<td class="first">
			&nbsp;
		</td>
		<td>
			inch
		</td>
		<td class="first">
			cm
		</td>
		<td>
			inch
		</td>
		<td class="first">
			cm
		</td>
		<td>
			inch
		</td>
		<td class="first">
			cm
		</td>
		<td>
			inch
		</td>
		<td class="first">
			cm
		</td>
		<td>
			inch
		</td>
		<td class="first">
			cm
		</td>
		<td>
			inch
		</td>
		<td class="first">
			cm
		</td>
		<td>
			inch
		</td>
		<td class="first">
			cm
		</td>
	</tr>
	<tr>
		<td class="first">
			Bust
		</td>
		<td>
			22
		</td>
		<td class="first">
			56
		</td>
		<td>
			24
		</td>
		<td class="first">
			61
		</td>
		<td>
			26
		</td>
		<td class="first">
			66
		</td>
		<td>
			28
		</td>
		<td class="first">
			71
		</td>
		<td>
			30
		</td>
		<td class="first">
			76
		</td>
		<td>
			32
		</td>
		<td class="first">
			81
		</td>
		<td>
			34
		</td>
		<td class="first">
			86
		</td>
	</tr>
	<tr>
		<td class="first">
			Waist
		</td>
		<td>
			20
		</td>
		<td class="first">
			51
		</td>
		<td>
			22
		</td>
		<td class="first">
			56
		</td>
		<td>
			24
		</td>
		<td class="first">
			61
		</td>
		<td>
			26
		</td>
		<td class="first">
			66
		</td>
		<td>
			28
		</td>
		<td class="first">
			71
		</td>
		<td>
			30
		</td>
		<td class="first">
			76
		</td>
		<td>
			32
		</td>
		<td class="first">
			81
		</td>
	</tr>
	<tr>
		<td class="first">
			Hips
		</td>
		<td>
			25
		</td>
		<td class="first">
			64
		</td>
		<td>
			27
		</td>
		<td class="first">
			69
		</td>
		<td>
			29
		</td>
		<td class="first">
			74
		</td>
		<td>
			31
		</td>
		<td class="first">
			79
		</td>
		<td>
			33
		</td>
		<td class="first">
			84
		</td>
		<td>
			35
		</td>
		<td class="first">
			89
		</td>
		<td>
			37
		</td>
		<td class="first">
			94
		</td>
	</tr>
	<tr>
		<td class="first">
			Hollow to Floor (Bare Foot)
		</td>
		<td>
			42
		</td>
		<td class="first">
			107
		</td>
		<td>
			45
		</td>
		<td class="first">
			114
		</td>
		<td>
			48
		</td>
		<td class="first">
			122
		</td>
		<td>
			50
		</td>
		<td class="first">
			127
		</td>
		<td>
			51
		</td>
		<td class="first">
			130
		</td>
		<td>
			53
		</td>
		<td class="first">
			135
		</td>
		<td>
			55
		</td>
		<td class="first">
			140
		</td>
	</tr>
	</tbody>
	</table>
	<div>
		<table class="chart-style" style="margin-top: 30px;" width="100%">
		<tbody>
		<tr>
			<td style="background: #f39; color: #fff;" colspan="27">
				<strong><span style="font-size: small; font-weight: normal;">Flower Girl Dresses Size Chart</span></strong>
			</td>
		</tr>
		<tr>
			<td class="first">
				Size
			</td>
			<td colspan="2">
				2
			</td>
			<td colspan="2">
				3
			</td>
			<td colspan="2">
				4
			</td>
			<td colspan="2">
				5
			</td>
			<td colspan="2">
				6
			</td>
			<td colspan="2">
				7
			</td>
			<td colspan="2">
				8
			</td>
			<td colspan="2">
				9
			</td>
			<td colspan="2">
				10
			</td>
			<td colspan="2">
				11
			</td>
			<td colspan="2">
				12
			</td>
			<td colspan="2">
				13
			</td>
			<td colspan="2">
				14
			</td>
		</tr>
		<tr>
			<td class="first">
				&nbsp;
			</td>
			<td>
				inch
			</td>
			<td class="first">
				cm
			</td>
			<td>
				inch
			</td>
			<td class="first">
				cm
			</td>
			<td>
				inch
			</td>
			<td class="first">
				cm
			</td>
			<td>
				inch
			</td>
			<td class="first">
				cm
			</td>
			<td>
				inch
			</td>
			<td class="first">
				cm
			</td>
			<td>
				inch
			</td>
			<td class="first">
				cm
			</td>
			<td>
				inch
			</td>
			<td class="first">
				cm
			</td>
			<td>
				inch
			</td>
			<td class="first">
				cm
			</td>
			<td>
				inch
			</td>
			<td class="first">
				cm
			</td>
			<td>
				inch
			</td>
			<td class="first">
				cm
			</td>
			<td>
				inch
			</td>
			<td class="first">
				cm
			</td>
			<td>
				inch
			</td>
			<td class="first">
				cm
			</td>
			<td>
				inch
			</td>
			<td class="first">
				cm
			</td>
		</tr>
		<tr>
			<td class="first">
				Bust
			</td>
			<td>
				21
			</td>
			<td class="first">
				53
			</td>
			<td>
				22
			</td>
			<td class="first">
				56
			</td>
			<td>
				23
			</td>
			<td class="first">
				58
			</td>
			<td>
				24
			</td>
			<td class="first">
				61
			</td>
			<td>
				25
			</td>
			<td class="first">
				64
			</td>
			<td>
				26
			</td>
			<td class="first">
				66
			</td>
			<td>
				27
			</td>
			<td class="first">
				69
			</td>
			<td>
				28
			</td>
			<td class="first">
				71
			</td>
			<td>
				29
			</td>
			<td class="first">
				74
			</td>
			<td>
				30.5
			</td>
			<td class="first">
				77
			</td>
			<td>
				32
			</td>
			<td class="first">
				81
			</td>
			<td>
				33
			</td>
			<td class="first">
				84
			</td>
			<td>
				34
			</td>
			<td class="first">
				86
			</td>
		</tr>
		<tr>
			<td class="first">
				Waist
			</td>
			<td>
				20
			</td>
			<td class="first">
				51
			</td>
			<td>
				21
			</td>
			<td class="first">
				53
			</td>
			<td>
				22
			</td>
			<td class="first">
				56
			</td>
			<td>
				23
			</td>
			<td class="first">
				58
			</td>
			<td>
				24
			</td>
			<td class="first">
				61
			</td>
			<td>
				25
			</td>
			<td class="first">
				64
			</td>
			<td>
				26
			</td>
			<td class="first">
				66
			</td>
			<td>
				27
			</td>
			<td class="first">
				69
			</td>
			<td>
				28
			</td>
			<td class="first">
				71
			</td>
			<td>
				29
			</td>
			<td class="first">
				74
			</td>
			<td>
				30
			</td>
			<td class="first">
				76
			</td>
			<td>
				31
			</td>
			<td class="first">
				79
			</td>
			<td>
				32
			</td>
			<td class="first">
				81
			</td>
		</tr>
		<tr>
			<td class="first">
				Hips
			</td>
			<td>
				20
			</td>
			<td class="first">
				51
			</td>
			<td>
				21
			</td>
			<td class="first">
				53
			</td>
			<td>
				22
			</td>
			<td class="first">
				56
			</td>
			<td>
				23
			</td>
			<td class="first">
				58
			</td>
			<td>
				25
			</td>
			<td class="first">
				64
			</td>
			<td>
				26
			</td>
			<td class="first">
				66
			</td>
			<td>
				27
			</td>
			<td class="first">
				69
			</td>
			<td>
				29
			</td>
			<td class="first">
				74
			</td>
			<td>
				31
			</td>
			<td class="first">
				79
			</td>
			<td>
				33
			</td>
			<td class="first">
				84
			</td>
			<td>
				34
			</td>
			<td class="first">
				86
			</td>
			<td>
				34.5
			</td>
			<td class="first">
				88
			</td>
			<td>
				35
			</td>
			<td class="first">
				89
			</td>
		</tr>
		<tr>
			<td class="first">
				Hollow to Floor (Bare Foot)
			</td>
			<td>
				33
			</td>
			<td class="first">
				84
			</td>
			<td>
				35
			</td>
			<td class="first">
				89
			</td>
			<td>
				38
			</td>
			<td class="first">
				97
			</td>
			<td>
				40
			</td>
			<td class="first">
				102
			</td>
			<td>
				41
			</td>
			<td class="first">
				104
			</td>
			<td>
				42
			</td>
			<td class="first">
				107
			</td>
			<td>
				43
			</td>
			<td class="first">
				109
			</td>
			<td>
				44
			</td>
			<td class="first">
				112
			</td>
			<td>
				47
			</td>
			<td class="first">
				119
			</td>
			<td>
				48
			</td>
			<td class="first">
				122
			</td>
			<td>
				50
			</td>
			<td class="first">
				127
			</td>
			<td>
				51
			</td>
			<td class="first">
				130
			</td>
			<td>
				52
			</td>
			<td class="first">
				132
			</td>
		</tr>
		</tbody>
		</table>
	</div>
	<style type="text/css">
#zzjs_nav3 table{border-top: 1px solid #ccc;border-left: 1px solid #ccc;}
#zzjs_nav3 table td{border-right: 1px solid #ccc;border-bottom: 1px solid #ccc;text-align:center;vertical-align: middle;}
	</style>
	<div id="zzjs_nav3">
		<table border="0" width="100%">
		<tbody>
		<tr>
			<td style="text-align: center; padding: 7px 0px; background: #f39; color: #fff;" colspan="8">
				<span>Bedding Size Chart</span>
			</td>
		</tr>
		<tr>
			<td style="color: #666;">
				Types
			</td>
			<td style="color: #666;">
				Cover
			</td>
			<td style="color: #666;">
				Sheet
			</td>
			<td style="color: #666;">
				Pillow cases
			</td>
		</tr>
		<tr>
			<td rowspan="2">
				Twin
			</td>
			<td>
				59"x 79"
			</td>
			<td>
				71" x 91"
			</td>
			<td>
				&nbsp;&nbsp;19" x 29"
			</td>
		</tr>
		<tr>
			<td>
				150 x 200 cm
			</td>
			<td>
				180 x 230 cm
			</td>
			<td>
				&nbsp;48 x 74 cm
			</td>
		</tr>
		<tr>
			<td rowspan="2">
				Extra Long Twin
			</td>
			<td>
				71"x 83"
			</td>
			<td>
				79" x 91"
			</td>
			<td>
				&nbsp;19" x 29"
			</td>
		</tr>
		<tr>
			<td>
				180 x 210 cm
			</td>
			<td>
				200 x 230 cm
			</td>
			<td>
				&nbsp;48 x 74 cm
			</td>
		</tr>
		<tr>
			<td rowspan="2">
				Full
			</td>
			<td>
				79" x 91"
			</td>
			<td>
				91"x 96"
			</td>
			<td>
				&nbsp;19" x 29"
			</td>
		</tr>
		<tr>
			<td>
				200 x 230 cm
			</td>
			<td>
				230 x 245 cm
			</td>
			<td>
				&nbsp;48 x 74 cm
			</td>
		</tr>
		<tr>
			<td rowspan="2">
				Queen
			</td>
			<td>
				88" x 90"
			</td>
			<td>
				90"x 98"
			</td>
			<td>
				&nbsp;19" x 29"
			</td>
		</tr>
		<tr>
			<td>
				224 x 229 cm
			</td>
			<td>
				229 x 249 cm
			</td>
			<td>
				&nbsp;48 x 74 cm
			</td>
		</tr>
		<tr>
			<td rowspan="2">
				King
			</td>
			<td>
				102" x 90"
			</td>
			<td>
				110"x 98"
			</td>
			<td>
				&nbsp;19" x 29"
			</td>
		</tr>
		<tr>
			<td>
				259x 229cm
			</td>
			<td>
				279 x 249cm
			</td>
			<td>
				&nbsp;48x 74cm
			</td>
		</tr>
		<tr>
			<td rowspan="2">
				California King
			</td>
			<td>
				106" x 92"
			</td>
			<td>
				108"x 102"
			</td>
			<td>
				&nbsp;20" x 36"
			</td>
		</tr>
		<tr>
			<td>
				269 x 234 cm
			</td>
			<td>
				274 x 259 cm
			</td>
			<td>
				&nbsp;51 x 91cm
			</td>
		</tr>
		</tbody>
		</table>
	</div>
	<style type="text/css">
table{border: 0;border-collapse: collapse;border-spacing: 0;empty-cells: show;font-size: 100%;}
strong{font-weight: bold;}
div.tabs-content{border-top:none;margin-bottom:10px;font:12px/17px Arial;overflow:hidden;clear:both;}
.chart-style{width: 100%;height: 260px;text-align: center;}
.chart-style, .chart-style tr, .chart-style td{border: 1px solid #CCC; font-family:Arial; font-size:12px;}
.chart-style td{text-align: center;vertical-align: middle;}
div#zzjs_nav3{  padding-top: 30px;}
.Chart table{  border-left: 1px solid #ccc;border-top: 1px solid #ccc;width: 100%;}
.wedthleft{color: #fff;font-size: 12px;font-family: Verdana;text-align: center;}
.Chart table th{ background: #f39;border-right: 1px solid #ccc;border-bottom: 1px solid #ccc;height: 30px;line-height: 30px;font-size: 11px;color: #fff;font-weight: normal;text-align: center;font-weight: bold;}
.Chart table td{  border-right: 1px solid #d1d1d1;border-bottom: 1px solid #d1d1d1;height: 20px;line-height: 20px;padding: 3px 5px;font-size: 12px;text-align: center; font-family:Arial;}
	</style>
	<style type="text/css">
.chart-style{width:100%;height:260px;text-align:center;}
					.chart-style td {text-align:center;vertical-align: middle;}
	</style>
	<style type="text/css">
#zzjs_nav1 .qh_tit{ font-size:12px; color:#fff; background:#f39; height:35px; line-height:35px; width:100%; text-align:center; font-family:Arial;}
#zzjs_nav1 table{border-left: 1px solid #ccc;border-top: 1px solid #ccc;width: 100%;}
#zzjs_nav1 table th{border-right: 1px solid #ccc;border-bottom: 1px solid #ccc;height: 20px;line-height: 20px;color: #666; padding: 0 5px;font-size: 12px;text-align: center;  background: none;}
#zzjs_nav1 table td{border-right: 1px solid #ccc;border-bottom: 1px solid #ccc;height: 20px;line-height: 20px;color: #666; padding: 0 5px;font-size: 12px;text-align: center;}
	</style>
	<div id="zzjs_nav1" class="Chart" style="margin-top: 30px; border-top-style: none; display: block;">
		<div class="qh_tit" style="padding-top: 0px; border-top-style: none;">
			Shoes Size Chart
		</div>
		<table class="chima2" border="0" width="100%">
		<tbody>
		<tr class="oushu">
			<th rowspan="2">
				US size
			</th>
			<th rowspan="2">
				EU size
			</th>
			<th rowspan="2">
				CN size
			</th>
			<th rowspan="2">
				UK size
			</th>
			<th rowspan="2">
				JP size
			</th>
			<th rowspan="2">
				AU size
			</th>
			<th>
				Foot length
			</th>
			<th>
				Foot length
			</th>
		</tr>
		<tr class="oushu">
			<th>
				inch
			</th>
			<th>
				mm
			</th>
		</tr>
		<tr>
			<td>
				5
			</td>
			<td>
				35
			</td>
			<td>
				34
			</td>
			<td>
				3
			</td>
			<td>
				225
			</td>
			<td>
				3.5
			</td>
			<td>
				8.66
			</td>
			<td>
				220
			</td>
		</tr>
		<tr class="oushu">
			<td>
				5.5
			</td>
			<td>
				36
			</td>
			<td>
				35
			</td>
			<td>
				3.5
			</td>
			<td>
				230
			</td>
			<td>
				4
			</td>
			<td>
				8.86
			</td>
			<td>
				225
			</td>
		</tr>
		<tr>
			<td>
				6
			</td>
			<td>
				36
			</td>
			<td>
				36
			</td>
			<td>
				4
			</td>
			<td>
				235
			</td>
			<td>
				4.5
			</td>
			<td>
				9.00
			</td>
			<td>
				230
			</td>
		</tr>
		<tr class="oushu">
			<td>
				6.5-7
			</td>
			<td>
				37
			</td>
			<td>
				37
			</td>
			<td>
				4.5-5
			</td>
			<td>
				245
			</td>
			<td>
				5-5.5
			</td>
			<td>
				9.25
			</td>
			<td>
				235
			</td>
		</tr>
		<tr>
			<td>
				7.5
			</td>
			<td>
				38
			</td>
			<td>
				38
			</td>
			<td>
				5.5
			</td>
			<td>
				250
			</td>
			<td>
				6
			</td>
			<td>
				9.44
			</td>
			<td>
				240
			</td>
		</tr>
		<tr class="oushu">
			<td>
				8
			</td>
			<td>
				39
			</td>
			<td>
				39
			</td>
			<td>
				6
			</td>
			<td>
				255
			</td>
			<td>
				6.5
			</td>
			<td>
				9.65
			</td>
			<td>
				245
			</td>
		</tr>
		<tr>
			<td>
				8.5
			</td>
			<td>
				39
			</td>
			<td>
				40
			</td>
			<td>
				6.5
			</td>
			<td>
				260
			</td>
			<td>
				7
			</td>
			<td>
				9.84
			</td>
			<td>
				250
			</td>
		</tr>
		<tr class="oushu">
			<td>
				9-9.5
			</td>
			<td>
				40
			</td>
			<td>
				41
			</td>
			<td>
				7
			</td>
			<td>
				275
			</td>
			<td>
				7.5
			</td>
			<td>
				10.00
			</td>
			<td>
				255
			</td>
		</tr>
		<tr>
			<td>
				10
			</td>
			<td>
				41
			</td>
			<td>
				42
			</td>
			<td>
				7.5-8
			</td>
			<td>
				280
			</td>
			<td>
				8-8.5
			</td>
			<td>
				10.23
			</td>
			<td>
				260
			</td>
		</tr>
		<tr class="oushu">
			<td>
				10.5
			</td>
			<td>
				42
			</td>
			<td>
				43
			</td>
			<td>
				8.5
			</td>
			<td>
				285
			</td>
			<td>
				9
			</td>
			<td>
				10.43
			</td>
			<td>
				265
			</td>
		</tr>
		<tr>
			<td>
				11
			</td>
			<td>
				43
			</td>
			<td>
				44
			</td>
			<td>
				9
			</td>
			<td>
				290
			</td>
			<td>
				9.5
			</td>
			<td>
				10.55
			</td>
			<td>
				270
			</td>
		</tr>
		<tr class="oushu">
			<td>
				11.5
			</td>
			<td>
				43
			</td>
			<td>
				45
			</td>
			<td>
				9.5
			</td>
			<td>
				295
			</td>
			<td>
				10
			</td>
			<td>
				10.80
			</td>
			<td>
				275 &frac12;
			</td>
		</tr>
		</tbody>
		</table>
	</div>
</div>